-- Videos actualizados con YouTube Data API v3
-- Generado: 2026-03-31T20:09:21.427Z

UPDATE semanas SET videos = '[{"titulo":"Salud Sexual y Reproductiva","titulo_en":"Salud Sexual y Reproductiva","url":"https://www.youtube.com/watch?v=F1WrfWtsdRY","url_en":"https://www.youtube.com/watch?v=F1WrfWtsdRY","duracion":"10 min"},{"titulo":"QUÉ SIGNIFICA EL ACRONIMO LGBT(QIA+) | #TELOEXPLICO","titulo_en":"QUÉ SIGNIFICA EL ACRONIMO LGBT(QIA+) | #TELOEXPLICO","url":"https://www.youtube.com/watch?v=Zkvz-5zVAIc","url_en":"https://www.youtube.com/watch?v=Zkvz-5zVAIc","duracion":"10 min"},{"titulo":"¿Ves lo que yo? (Cortometraje sobre violencia de género)","titulo_en":"¿Ves lo que yo? (Cortometraje sobre violencia de género)","url":"https://www.youtube.com/watch?v=Id0KeN49jHY","url_en":"https://www.youtube.com/watch?v=Id0KeN49jHY","duracion":"10 min"}]'::jsonb
WHERE id = 'd6979814-1791-4931-913b-9d9084c7af61';

UPDATE semanas SET videos = '[{"titulo":"Las FUNCIONES del LENGUAJE - Explicación con ejemplos I TeoCom","titulo_en":"Las FUNCIONES del LENGUAJE - Explicación con ejemplos I TeoCom","url":"https://www.youtube.com/watch?v=UJxSAq54HkA","url_en":"https://www.youtube.com/watch?v=UJxSAq54HkA","duracion":"10 min"},{"titulo":"¿Qué es la comunicación? Proceso y elementos de la comunicación 🗣","titulo_en":"¿Qué es la comunicación? Proceso y elementos de la comunicación 🗣","url":"https://www.youtube.com/watch?v=KujFJsEOPTs","url_en":"https://www.youtube.com/watch?v=KujFJsEOPTs","duracion":"10 min"},{"titulo":"Los TIPOS DE LENGUAJE: cuáles son, características y ejemplos💬","titulo_en":"Los TIPOS DE LENGUAJE: cuáles son, características y ejemplos💬","url":"https://www.youtube.com/watch?v=lYNBSp5a3RA","url_en":"https://www.youtube.com/watch?v=lYNBSp5a3RA","duracion":"10 min"}]'::jsonb
WHERE id = '1e09048e-517d-4192-91f5-a39911b5567b';

UPDATE semanas SET videos = '[{"titulo":"Determinantes de la Salud  Determinantes sociales de la salud Factores sociales de la Salud","titulo_en":"Determinantes de la Salud  Determinantes sociales de la salud Factores sociales de la Salud","url":"https://www.youtube.com/watch?v=-LHCRNfTzVo","url_en":"https://www.youtube.com/watch?v=-LHCRNfTzVo","duracion":"10 min"},{"titulo":"Un Trip de Salud Mental | Casi Creativo","titulo_en":"Un Trip de Salud Mental | Casi Creativo","url":"https://www.youtube.com/watch?v=JQr6Ld8d-f8","url_en":"https://www.youtube.com/watch?v=JQr6Ld8d-f8","duracion":"10 min"},{"titulo":"Como Hacer un TRÍPTICO - Fácil - Día Mundial de la salud","titulo_en":"Como Hacer un TRÍPTICO - Fácil - Día Mundial de la salud","url":"https://www.youtube.com/watch?v=ZGMcdUFqBw4","url_en":"https://www.youtube.com/watch?v=ZGMcdUFqBw4","duracion":"10 min"}]'::jsonb
WHERE id = 'bc691cdb-e9b9-4add-9a25-aa96487d6399';

UPDATE semanas SET videos = '[{"titulo":"La Civilización MAYA - Resumen | Origen, política, sociedad, economía, religión, arquitectura...","titulo_en":"La Civilización MAYA - Resumen | Origen, política, sociedad, economía, religión, arquitectura...","url":"https://www.youtube.com/watch?v=J-3n1FFH6LQ","url_en":"https://www.youtube.com/watch?v=J-3n1FFH6LQ","duracion":"10 min"},{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"},{"titulo":"¿Cómo se formaron las Primeras CIVILIZACIONES? - Resumen | El Surgimiento de la Civilización.","titulo_en":"¿Cómo se formaron las Primeras CIVILIZACIONES? - Resumen | El Surgimiento de la Civilización.","url":"https://www.youtube.com/watch?v=WeVIhWd_eIk","url_en":"https://www.youtube.com/watch?v=WeVIhWd_eIk","duracion":"10 min"}]'::jsonb
WHERE id = '71c3e3c7-67ca-4b79-8c3c-b8bb83a7b06d';

UPDATE semanas SET videos = '[{"titulo":"TIPS PARA EL PRIMER DÍA DE CLASES: Consejos para Profesores!","titulo_en":"TIPS PARA EL PRIMER DÍA DE CLASES: Consejos para Profesores!","url":"https://www.youtube.com/watch?v=1X2d40mAXKM","url_en":"https://www.youtube.com/watch?v=1X2d40mAXKM","duracion":"10 min"},{"titulo":"¡Conoce nuestra metodología de estudio en línea!","titulo_en":"¡Conoce nuestra metodología de estudio en línea!","url":"https://www.youtube.com/watch?v=v071y14yQIU","url_en":"https://www.youtube.com/watch?v=v071y14yQIU","duracion":"10 min"},{"titulo":"Curso de Scratch 3.0 desde cero🙀 Para principiantes","titulo_en":"Curso de Scratch 3.0 desde cero🙀 Para principiantes","url":"https://www.youtube.com/watch?v=a5DOIvjxiQ0","url_en":"https://www.youtube.com/watch?v=a5DOIvjxiQ0","duracion":"10 min"}]'::jsonb
WHERE id = '4d69b117-365d-4985-8378-8da9c3c0d17a';

UPDATE semanas SET videos = '[{"titulo":"✔🔝SISTEMAS OPERATIVOS | ¿Que son?¿Como Funcionan? | TIPOS de SISTEMAS OPERATIVOS | Explicación Facil","titulo_en":"✔🔝SISTEMAS OPERATIVOS | ¿Que son?¿Como Funcionan? | TIPOS de SISTEMAS OPERATIVOS | Explicación Facil","url":"https://www.youtube.com/watch?v=fsuroRYmagw","url_en":"https://www.youtube.com/watch?v=fsuroRYmagw","duracion":"10 min"},{"titulo":"Historia y Evolución de las Computadoras y sus Generaciones ✅","titulo_en":"Historia y Evolución de las Computadoras y sus Generaciones ✅","url":"https://www.youtube.com/watch?v=wD8yJnIG7gI","url_en":"https://www.youtube.com/watch?v=wD8yJnIG7gI","duracion":"10 min"},{"titulo":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","titulo_en":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","url":"https://www.youtube.com/watch?v=_JNPvSxG6oM","url_en":"https://www.youtube.com/watch?v=_JNPvSxG6oM","duracion":"10 min"}]'::jsonb
WHERE id = '8abefc27-cec7-4781-bbe4-529ae88d7866';

UPDATE semanas SET videos = '[{"titulo":"Niveles de comprensión lectora.","titulo_en":"Niveles de comprensión lectora.","url":"https://www.youtube.com/watch?v=f0fXjNj9QYI","url_en":"https://www.youtube.com/watch?v=f0fXjNj9QYI","duracion":"10 min"},{"titulo":"Niveles de comprensión lectora con ejemplo de lectura 📖","titulo_en":"Niveles de comprensión lectora con ejemplo de lectura 📖","url":"https://www.youtube.com/watch?v=sjPND6xYuTo","url_en":"https://www.youtube.com/watch?v=sjPND6xYuTo","duracion":"10 min"},{"titulo":"😮 Las 7 Mejores Técnicas de Comprensión Lectora (Fácil y con Ejemplos) | Curso de Lectura #8","titulo_en":"😮 Las 7 Mejores Técnicas de Comprensión Lectora (Fácil y con Ejemplos) | Curso de Lectura #8","url":"https://www.youtube.com/watch?v=TmtJZGI18R0","url_en":"https://www.youtube.com/watch?v=TmtJZGI18R0","duracion":"10 min"}]'::jsonb
WHERE id = '79d2b13e-8665-477b-95c0-c3df47cfd6a3';

UPDATE semanas SET videos = '[{"titulo":"Productos notables, conceptos previos","titulo_en":"Productos notables, conceptos previos","url":"https://www.youtube.com/watch?v=G-ym95yl3Es","url_en":"https://www.youtube.com/watch?v=G-ym95yl3Es","duracion":"10 min"},{"titulo":"PRODUCTOS NOTABLES: Suma y resta de un binomio al cuadrado. Producto de dos binomios conjugados","titulo_en":"PRODUCTOS NOTABLES: Suma y resta de un binomio al cuadrado. Producto de dos binomios conjugados","url":"https://www.youtube.com/watch?v=R58oWfchP5c","url_en":"https://www.youtube.com/watch?v=R58oWfchP5c","duracion":"10 min"},{"titulo":"Productos Notables | Fórmulas y Ejemplos","titulo_en":"Productos Notables | Fórmulas y Ejemplos","url":"https://www.youtube.com/watch?v=eHDIhEjE3c0","url_en":"https://www.youtube.com/watch?v=eHDIhEjE3c0","duracion":"10 min"}]'::jsonb
WHERE id = 'fbf6dcaa-8fbe-46b3-a804-fcc5dc9eb901';

UPDATE semanas SET videos = '[{"titulo":"Present simple vs Present continuous first video, Presente simple vs Presente continuo primer video","titulo_en":"Present simple vs Present continuous first video, Presente simple vs Presente continuo primer video","url":"https://www.youtube.com/watch?v=3B_6pS8a0jk","url_en":"https://www.youtube.com/watch?v=3B_6pS8a0jk","duracion":"10 min"},{"titulo":"Diferencia entre PRESENTE SIMPLE y PRESENTE CONTINUO en inglés","titulo_en":"Diferencia entre PRESENTE SIMPLE y PRESENTE CONTINUO en inglés","url":"https://www.youtube.com/watch?v=57v-YdOBGTY","url_en":"https://www.youtube.com/watch?v=57v-YdOBGTY","duracion":"10 min"},{"titulo":"👉DIFERENCIAS ENTRE PRESENTE SIMPLE Y PRESENTE CONTINUO EN INGLÉS","titulo_en":"👉DIFERENCIAS ENTRE PRESENTE SIMPLE Y PRESENTE CONTINUO EN INGLÉS","url":"https://www.youtube.com/watch?v=daYBW1I99yc","url_en":"https://www.youtube.com/watch?v=daYBW1I99yc","duracion":"10 min"}]'::jsonb
WHERE id = 'acc99942-8299-42ba-8ee8-ef1d0173d1fa';

UPDATE semanas SET videos = '[{"titulo":"Sistemas numéricos: Binario, Decimal y Hexadecimal","titulo_en":"Sistemas numéricos: Binario, Decimal y Hexadecimal","url":"https://www.youtube.com/watch?v=g9-MRBBcvdg","url_en":"https://www.youtube.com/watch?v=g9-MRBBcvdg","duracion":"10 min"},{"titulo":"CONJUNTOS NUMÉRICOS | Explicación detallada | MUY FÁCIL 🤩 |","titulo_en":"CONJUNTOS NUMÉRICOS | Explicación detallada | MUY FÁCIL 🤩 |","url":"https://www.youtube.com/watch?v=RDn8UdSnN8Q","url_en":"https://www.youtube.com/watch?v=RDn8UdSnN8Q","duracion":"10 min"},{"titulo":"Números Binarios | Introducción","titulo_en":"Números Binarios | Introducción","url":"https://www.youtube.com/watch?v=F1xB6oxmMWQ","url_en":"https://www.youtube.com/watch?v=F1xB6oxmMWQ","duracion":"10 min"}]'::jsonb
WHERE id = 'dc5f3cb2-c6cb-489f-92d6-7644cdbe4276';

UPDATE semanas SET videos = '[{"titulo":"🔴 SALUDOS Y DESPEDIDAS EN INGLÉS MÁS COMUNES CON EJEMPLOS 🌈","titulo_en":"🔴 SALUDOS Y DESPEDIDAS EN INGLÉS MÁS COMUNES CON EJEMPLOS 🌈","url":"https://www.youtube.com/watch?v=fbVEFymdUtk","url_en":"https://www.youtube.com/watch?v=fbVEFymdUtk","duracion":"10 min"},{"titulo":"EL ABECEDARIO en inglés 🔊PRONUNCIACIÓN fácil y rápido🚀 ▶ [＃2 Clase]","titulo_en":"EL ABECEDARIO en inglés 🔊PRONUNCIACIÓN fácil y rápido🚀 ▶ [＃2 Clase]","url":"https://www.youtube.com/watch?v=bGLbYVFzMwk","url_en":"https://www.youtube.com/watch?v=bGLbYVFzMwk","duracion":"10 min"},{"titulo":"SALUDOS Y DESPEDIDAS EN INGLES / LOS MAS USADOS EN ESTADOS UNIDOS","titulo_en":"SALUDOS Y DESPEDIDAS EN INGLES / LOS MAS USADOS EN ESTADOS UNIDOS","url":"https://www.youtube.com/watch?v=uim7QYa8Ado","url_en":"https://www.youtube.com/watch?v=uim7QYa8Ado","duracion":"10 min"}]'::jsonb
WHERE id = '6d973d65-35a8-4039-821d-8a641e347452';

UPDATE semanas SET videos = '[{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"},{"titulo":"HISTORIA - Origen y Evolución del Español o Castellano | MINI-DOCUMENTAL","titulo_en":"HISTORIA - Origen y Evolución del Español o Castellano | MINI-DOCUMENTAL","url":"https://www.youtube.com/watch?v=ZpAdq8sb5iI","url_en":"https://www.youtube.com/watch?v=ZpAdq8sb5iI","duracion":"10 min"},{"titulo":"El HUMANISMO Renacentista - Resumen | Definición, Características y Principales Representantes.","titulo_en":"El HUMANISMO Renacentista - Resumen | Definición, Características y Principales Representantes.","url":"https://www.youtube.com/watch?v=EmS0eeY8Osk","url_en":"https://www.youtube.com/watch?v=EmS0eeY8Osk","duracion":"10 min"}]'::jsonb
WHERE id = '58159d95-28fc-4752-af37-d9e03a1c42a5';

UPDATE semanas SET videos = '[{"titulo":"Uso responsable de la tecnología para niños - Primer móvil - Ciberbullying - Fake news - Privacidad","titulo_en":"Uso responsable de la tecnología para niños - Primer móvil - Ciberbullying - Fake news - Privacidad","url":"https://www.youtube.com/watch?v=tBObvkx_nOg","url_en":"https://www.youtube.com/watch?v=tBObvkx_nOg","duracion":"10 min"},{"titulo":"¿Qué es Google WorkSpace, para qué sirve y cómo funciona? 😎 Guía Principiantes","titulo_en":"¿Qué es Google WorkSpace, para qué sirve y cómo funciona? 😎 Guía Principiantes","url":"https://www.youtube.com/watch?v=aSWIQJw3o0k","url_en":"https://www.youtube.com/watch?v=aSWIQJw3o0k","duracion":"10 min"},{"titulo":"Uso correcto de las redes sociales","titulo_en":"Uso correcto de las redes sociales","url":"https://www.youtube.com/watch?v=wHkj1qLUtfk","url_en":"https://www.youtube.com/watch?v=wHkj1qLUtfk","duracion":"10 min"}]'::jsonb
WHERE id = '722df124-98de-4a7a-b4ad-4309e85d810f';

UPDATE semanas SET videos = '[{"titulo":"INTRODUCCIÓN AL ESTUDIO DEL DERECHO","titulo_en":"INTRODUCCIÓN AL ESTUDIO DEL DERECHO","url":"https://www.youtube.com/watch?v=D0xpwXToys4","url_en":"https://www.youtube.com/watch?v=D0xpwXToys4","duracion":"10 min"},{"titulo":"7 pasos para aprender más fácil, rápido y mejor con la IA","titulo_en":"7 pasos para aprender más fácil, rápido y mejor con la IA","url":"https://www.youtube.com/watch?v=BodjJNp8KMw","url_en":"https://www.youtube.com/watch?v=BodjJNp8KMw","duracion":"10 min"},{"titulo":"🔎PROCESO DE INVESTIGACIÓN🌎 Paso a paso - Aprender a investigar💛","titulo_en":"🔎PROCESO DE INVESTIGACIÓN🌎 Paso a paso - Aprender a investigar💛","url":"https://www.youtube.com/watch?v=iTGGl8KAoLU","url_en":"https://www.youtube.com/watch?v=iTGGl8KAoLU","duracion":"10 min"}]'::jsonb
WHERE id = '9c640e06-5523-45d2-a923-aaab300be291';

UPDATE semanas SET videos = '[{"titulo":"OPERACIONES COMBINADAS Super facil - Para principiantes","titulo_en":"OPERACIONES COMBINADAS Super facil - Para principiantes","url":"https://www.youtube.com/watch?v=w016sdtyv1w","url_en":"https://www.youtube.com/watch?v=w016sdtyv1w","duracion":"10 min"},{"titulo":"JERARQUÍA DE LAS OPERACIONES Superfácil - Para principiantes","titulo_en":"JERARQUÍA DE LAS OPERACIONES Superfácil - Para principiantes","url":"https://www.youtube.com/watch?v=XV5PiV2-91U","url_en":"https://www.youtube.com/watch?v=XV5PiV2-91U","duracion":"10 min"},{"titulo":"Jerarquía de las operaciones. Explicación a detalle de dos ejemplos","titulo_en":"Jerarquía de las operaciones. Explicación a detalle de dos ejemplos","url":"https://www.youtube.com/watch?v=i684TUoMPFc","url_en":"https://www.youtube.com/watch?v=i684TUoMPFc","duracion":"10 min"}]'::jsonb
WHERE id = '98bc88c3-5587-487a-a992-b7f957a538d6';

UPDATE semanas SET videos = '[{"titulo":"INTRODUCCIÓN A ALGORITMOS - Ideas y conceptos básicos","titulo_en":"INTRODUCCIÓN A ALGORITMOS - Ideas y conceptos básicos","url":"https://www.youtube.com/watch?v=f10jKIslSUY","url_en":"https://www.youtube.com/watch?v=f10jKIslSUY","duracion":"10 min"},{"titulo":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","titulo_en":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","url":"https://www.youtube.com/watch?v=as1opL254NA","url_en":"https://www.youtube.com/watch?v=as1opL254NA","duracion":"10 min"},{"titulo":"🔴 ¿ Qué es un DIAGRAMA DE FLUJO ? 🔼 Cómo HACER Diagramas de Flujo Paso a Paso + Ejemplos","titulo_en":"🔴 ¿ Qué es un DIAGRAMA DE FLUJO ? 🔼 Cómo HACER Diagramas de Flujo Paso a Paso + Ejemplos","url":"https://www.youtube.com/watch?v=Kucgc6NpGwc","url_en":"https://www.youtube.com/watch?v=Kucgc6NpGwc","duracion":"10 min"}]'::jsonb
WHERE id = '42188cf0-df4c-4dee-a39f-d570324abeda';

UPDATE semanas SET videos = '[{"titulo":"PASADO SIMPLE EN INGLÉS: ¡domínalo de una vez por todas!","titulo_en":"PASADO SIMPLE EN INGLÉS: ¡domínalo de una vez por todas!","url":"https://www.youtube.com/watch?v=F8aEosp-bFk","url_en":"https://www.youtube.com/watch?v=F8aEosp-bFk","duracion":"10 min"},{"titulo":"INGLÉS BÁSICO: EL PASADO | Superholly","titulo_en":"INGLÉS BÁSICO: EL PASADO | Superholly","url":"https://www.youtube.com/watch?v=GcTSbETuREw","url_en":"https://www.youtube.com/watch?v=GcTSbETuREw","duracion":"10 min"},{"titulo":"Pasado simple en inglés.✅ Inglés para principiantes.","titulo_en":"Pasado simple en inglés.✅ Inglés para principiantes.","url":"https://www.youtube.com/watch?v=6uqRJSBoXJU","url_en":"https://www.youtube.com/watch?v=6uqRJSBoXJU","duracion":"10 min"}]'::jsonb
WHERE id = 'fb1d4456-c594-4bf8-bb26-8141dbc0bace';

UPDATE semanas SET videos = '[{"titulo":"📖 4 Técnicas para MEJORAR tu COMPRENSIÓN de LECTURA | Técnicas de Estudio #5","titulo_en":"📖 4 Técnicas para MEJORAR tu COMPRENSIÓN de LECTURA | Técnicas de Estudio #5","url":"https://www.youtube.com/watch?v=mJzOLghzUwA","url_en":"https://www.youtube.com/watch?v=mJzOLghzUwA","duracion":"10 min"},{"titulo":"8 estrategias para MEJORAR tu COMPRENSIÓN LECTORA","titulo_en":"8 estrategias para MEJORAR tu COMPRENSIÓN LECTORA","url":"https://www.youtube.com/watch?v=rkWb3uAGSSw","url_en":"https://www.youtube.com/watch?v=rkWb3uAGSSw","duracion":"10 min"},{"titulo":"Formación Cívica y Ética. Estrategias de comprensión lectora, Bachillerato.","titulo_en":"Formación Cívica y Ética. Estrategias de comprensión lectora, Bachillerato.","url":"https://www.youtube.com/watch?v=XR8lmHKPxh4","url_en":"https://www.youtube.com/watch?v=XR8lmHKPxh4","duracion":"10 min"}]'::jsonb
WHERE id = 'efdb546e-1924-4771-898e-ec8c964498e8';

UPDATE semanas SET videos = '[{"titulo":"FACTORIZACIÓN POR FACTOR COMÚN Super facil  - Para principiantes","titulo_en":"FACTORIZACIÓN POR FACTOR COMÚN Super facil  - Para principiantes","url":"https://www.youtube.com/watch?v=BygK11QxQnA","url_en":"https://www.youtube.com/watch?v=BygK11QxQnA","duracion":"10 min"},{"titulo":"FACTORIZACIÓN. ¿Sabes factorizar este polinomio?","titulo_en":"FACTORIZACIÓN. ¿Sabes factorizar este polinomio?","url":"https://www.youtube.com/watch?v=yRa_g6ZVpQ4","url_en":"https://www.youtube.com/watch?v=yRa_g6ZVpQ4","duracion":"10 min"},{"titulo":"FACTORIZAR UN TRINOMIO CUADRADO PERFECTO","titulo_en":"FACTORIZAR UN TRINOMIO CUADRADO PERFECTO","url":"https://www.youtube.com/watch?v=TKo7NtIilWM","url_en":"https://www.youtube.com/watch?v=TKo7NtIilWM","duracion":"10 min"}]'::jsonb
WHERE id = '02deb5bf-d237-48dc-9533-97d161f2329f';

UPDATE semanas SET videos = '[{"titulo":"ANATOMÍA del aparato REPRODUCTOR FEMENINO. Completo y fácil","titulo_en":"ANATOMÍA del aparato REPRODUCTOR FEMENINO. Completo y fácil","url":"https://www.youtube.com/watch?v=kLMbfsM7iAE","url_en":"https://www.youtube.com/watch?v=kLMbfsM7iAE","duracion":"10 min"},{"titulo":"Fisiología del Ciclo Sexual Femenino: hormonal, ovárico y uterino. #ENARM","titulo_en":"Fisiología del Ciclo Sexual Femenino: hormonal, ovárico y uterino. #ENARM","url":"https://www.youtube.com/watch?v=B9Zaxu58TSw","url_en":"https://www.youtube.com/watch?v=B9Zaxu58TSw","duracion":"10 min"},{"titulo":"Anatomía y Fisiología del Aparato reproductor masculino","titulo_en":"Anatomía y Fisiología del Aparato reproductor masculino","url":"https://www.youtube.com/watch?v=tRRlv3Cnxug","url_en":"https://www.youtube.com/watch?v=tRRlv3Cnxug","duracion":"10 min"}]'::jsonb
WHERE id = '169c2b59-5dbb-47a8-877b-6063e07dbb48';

UPDATE semanas SET videos = '[{"titulo":"Aprende a diferenciar los tipos de textos o las Tipologías Textuales","titulo_en":"Aprende a diferenciar los tipos de textos o las Tipologías Textuales","url":"https://www.youtube.com/watch?v=mKqa49RKnC4","url_en":"https://www.youtube.com/watch?v=mKqa49RKnC4","duracion":"10 min"},{"titulo":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","titulo_en":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","url":"https://www.youtube.com/watch?v=tMP1lds7pLM","url_en":"https://www.youtube.com/watch?v=tMP1lds7pLM","duracion":"10 min"},{"titulo":"Las FUNCIONES del LENGUAJE - Explicación con ejemplos I TeoCom","titulo_en":"Las FUNCIONES del LENGUAJE - Explicación con ejemplos I TeoCom","url":"https://www.youtube.com/watch?v=UJxSAq54HkA","url_en":"https://www.youtube.com/watch?v=UJxSAq54HkA","duracion":"10 min"}]'::jsonb
WHERE id = '0847342e-925d-4dcf-a2f1-43e55e78d66c';

UPDATE semanas SET videos = '[{"titulo":"Todos los PRONOMBRES en INGLÉS explicados fácilmente","titulo_en":"Todos los PRONOMBRES en INGLÉS explicados fácilmente","url":"https://www.youtube.com/watch?v=rFZQmXjALbU","url_en":"https://www.youtube.com/watch?v=rFZQmXjALbU","duracion":"10 min"},{"titulo":"✅ Verbo TO BE en inglés para principiantes (AM, ARE, IS) - Curso de Inglés","titulo_en":"✅ Verbo TO BE en inglés para principiantes (AM, ARE, IS) - Curso de Inglés","url":"https://www.youtube.com/watch?v=phP_PKBzrsg","url_en":"https://www.youtube.com/watch?v=phP_PKBzrsg","duracion":"10 min"},{"titulo":"Como usar el VERBO TO BE POSITIVO, NEGATIVO Y PREGUNTAS |  en inglés con ejemplos","titulo_en":"Como usar el VERBO TO BE POSITIVO, NEGATIVO Y PREGUNTAS |  en inglés con ejemplos","url":"https://www.youtube.com/watch?v=oeksGYoNaXE","url_en":"https://www.youtube.com/watch?v=oeksGYoNaXE","duracion":"10 min"}]'::jsonb
WHERE id = '4e0bdc06-b10f-49f5-a0f6-7089076e9f2b';

UPDATE semanas SET videos = '[{"titulo":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","titulo_en":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","url":"https://www.youtube.com/watch?v=qHimbDfTXYg","url_en":"https://www.youtube.com/watch?v=qHimbDfTXYg","duracion":"10 min"},{"titulo":"¿Qué es un CUADRO COMPARATIVO y cómo se hace? Características y EJEMPLOS👩‍🏫","titulo_en":"¿Qué es un CUADRO COMPARATIVO y cómo se hace? Características y EJEMPLOS👩‍🏫","url":"https://www.youtube.com/watch?v=94nISi7DYNU","url_en":"https://www.youtube.com/watch?v=94nISi7DYNU","duracion":"10 min"}]'::jsonb
WHERE id = '075a4ebf-4563-41ee-aa80-4b5d1f63b140';

UPDATE semanas SET videos = '[{"titulo":"Los Miembros de la Familia en Inglés: los familiares en inglés","titulo_en":"Los Miembros de la Familia en Inglés: los familiares en inglés","url":"https://www.youtube.com/watch?v=RPgrB2CVi3U","url_en":"https://www.youtube.com/watch?v=RPgrB2CVi3U","duracion":"10 min"},{"titulo":"Emociones en Inglés | Sentimientos en Inglés Para Niños","titulo_en":"Emociones en Inglés | Sentimientos en Inglés Para Niños","url":"https://www.youtube.com/watch?v=aT9CKFC9D2c","url_en":"https://www.youtube.com/watch?v=aT9CKFC9D2c","duracion":"10 min"},{"titulo":"Los NÚMEROS en inglés: ¡Del 0 al infinito!","titulo_en":"Los NÚMEROS en inglés: ¡Del 0 al infinito!","url":"https://www.youtube.com/watch?v=wGwDQMph5dk","url_en":"https://www.youtube.com/watch?v=wGwDQMph5dk","duracion":"10 min"}]'::jsonb
WHERE id = 'f499bb47-47ca-43d1-8aec-9407af6a789b';

UPDATE semanas SET videos = '[{"titulo":"Textos informativos |  Características, estructura y tipos de textos expositivos","titulo_en":"Textos informativos |  Características, estructura y tipos de textos expositivos","url":"https://www.youtube.com/watch?v=n7RIOiCh44Q","url_en":"https://www.youtube.com/watch?v=n7RIOiCh44Q","duracion":"10 min"},{"titulo":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","titulo_en":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","url":"https://www.youtube.com/watch?v=tMP1lds7pLM","url_en":"https://www.youtube.com/watch?v=tMP1lds7pLM","duracion":"10 min"},{"titulo":"TEXTOS INFORMATIVOS 📝 | Características, estructura y elementos 🤓","titulo_en":"TEXTOS INFORMATIVOS 📝 | Características, estructura y elementos 🤓","url":"https://www.youtube.com/watch?v=AzSuzfrWtDY","url_en":"https://www.youtube.com/watch?v=AzSuzfrWtDY","duracion":"10 min"}]'::jsonb
WHERE id = '055cfb28-2853-4fc3-b55e-1ad5ad8a72c9';

UPDATE semanas SET videos = '[{"titulo":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","titulo_en":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","url":"https://www.youtube.com/watch?v=qHimbDfTXYg","url_en":"https://www.youtube.com/watch?v=qHimbDfTXYg","duracion":"10 min"},{"titulo":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","titulo_en":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","url":"https://www.youtube.com/watch?v=YWGOThGG8-Y","url_en":"https://www.youtube.com/watch?v=YWGOThGG8-Y","duracion":"10 min"},{"titulo":"Como tener un estilo de vida saludable","titulo_en":"Como tener un estilo de vida saludable","url":"https://www.youtube.com/watch?v=8npDqV_ML1o","url_en":"https://www.youtube.com/watch?v=8npDqV_ML1o","duracion":"10 min"}]'::jsonb
WHERE id = '706f3daa-dc18-4bf6-9a4c-c56d32487d2b';

UPDATE semanas SET videos = '[{"titulo":"Cómo usar Google Docs - Editor de Documentos de Google 2025","titulo_en":"Cómo usar Google Docs - Editor de Documentos de Google 2025","url":"https://www.youtube.com/watch?v=xApZhkNcJyY","url_en":"https://www.youtube.com/watch?v=xApZhkNcJyY","duracion":"10 min"},{"titulo":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","titulo_en":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","url":"https://www.youtube.com/watch?v=tMP1lds7pLM","url_en":"https://www.youtube.com/watch?v=tMP1lds7pLM","duracion":"10 min"},{"titulo":"Qué es y Cómo hacer una MICROCLASE | Planificación y Ejemplos 👩🏼‍🏫📓","titulo_en":"Qué es y Cómo hacer una MICROCLASE | Planificación y Ejemplos 👩🏼‍🏫📓","url":"https://www.youtube.com/watch?v=Lw81tarHizA","url_en":"https://www.youtube.com/watch?v=Lw81tarHizA","duracion":"10 min"}]'::jsonb
WHERE id = '0368b63a-aee7-412a-8f2a-4bbbfd0efd43';

UPDATE semanas SET videos = '[{"titulo":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","titulo_en":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","url":"https://www.youtube.com/watch?v=as1opL254NA","url_en":"https://www.youtube.com/watch?v=as1opL254NA","duracion":"10 min"},{"titulo":"INTRODUCCIÓN A ALGORITMOS - Ideas y conceptos básicos","titulo_en":"INTRODUCCIÓN A ALGORITMOS - Ideas y conceptos básicos","url":"https://www.youtube.com/watch?v=f10jKIslSUY","url_en":"https://www.youtube.com/watch?v=f10jKIslSUY","duracion":"10 min"},{"titulo":"Aprende PYTHON en 10 minutos 🟢","titulo_en":"Aprende PYTHON en 10 minutos 🟢","url":"https://www.youtube.com/watch?v=_6N18g3ewnw","url_en":"https://www.youtube.com/watch?v=_6N18g3ewnw","duracion":"10 min"}]'::jsonb
WHERE id = 'b8a4c6d1-54a5-4906-98a6-f1433d47419d';

UPDATE semanas SET videos = '[{"titulo":"Salud Sexual y Reproductiva","titulo_en":"Salud Sexual y Reproductiva","url":"https://www.youtube.com/watch?v=F1WrfWtsdRY","url_en":"https://www.youtube.com/watch?v=F1WrfWtsdRY","duracion":"10 min"},{"titulo":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","titulo_en":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","url":"https://www.youtube.com/watch?v=F6_QXn0GcdI","url_en":"https://www.youtube.com/watch?v=F6_QXn0GcdI","duracion":"10 min"},{"titulo":"¿Cómo funciona el cerebro de un adolescente? David Bueno, biólogo y genetista","titulo_en":"¿Cómo funciona el cerebro de un adolescente? David Bueno, biólogo y genetista","url":"https://www.youtube.com/watch?v=v4KplEgXI9c","url_en":"https://www.youtube.com/watch?v=v4KplEgXI9c","duracion":"10 min"}]'::jsonb
WHERE id = '98f431a1-b299-49c5-a947-8141786cc878';

UPDATE semanas SET videos = '[{"titulo":"Ecuaciones con paréntesis y fracciones","titulo_en":"Ecuaciones con paréntesis y fracciones","url":"https://www.youtube.com/watch?v=EIYgVNc2iz4","url_en":"https://www.youtube.com/watch?v=EIYgVNc2iz4","duracion":"10 min"},{"titulo":"Cómo solucionar ecuaciones de primer grado con fracciones | Ejemplo 1","titulo_en":"Cómo solucionar ecuaciones de primer grado con fracciones | Ejemplo 1","url":"https://www.youtube.com/watch?v=qud71ShXTK4","url_en":"https://www.youtube.com/watch?v=qud71ShXTK4","duracion":"10 min"},{"titulo":"SISTEMAS de Ecuaciones con PARÉNTESIS y FRACCIONES 🔢","titulo_en":"SISTEMAS de Ecuaciones con PARÉNTESIS y FRACCIONES 🔢","url":"https://www.youtube.com/watch?v=ZmuigZOjgk0","url_en":"https://www.youtube.com/watch?v=ZmuigZOjgk0","duracion":"10 min"}]'::jsonb
WHERE id = 'e869bd2c-84c2-49ad-83ca-4dccc6f89cf6';

UPDATE semanas SET videos = '[{"titulo":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","titulo_en":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","url":"https://www.youtube.com/watch?v=-8YazHRMcXk","url_en":"https://www.youtube.com/watch?v=-8YazHRMcXk","duracion":"10 min"},{"titulo":"📝 10 Técnicas para ESTUDIAR y APROBAR un EXAMEN de ADMISIÓN | (Técnicas de Estudio #10)","titulo_en":"📝 10 Técnicas para ESTUDIAR y APROBAR un EXAMEN de ADMISIÓN | (Técnicas de Estudio #10)","url":"https://www.youtube.com/watch?v=FP04a7za8Ts","url_en":"https://www.youtube.com/watch?v=FP04a7za8Ts","duracion":"10 min"},{"titulo":"Las mejores técnicas de estudio, memorización rápida y aprendizaje productivo","titulo_en":"Las mejores técnicas de estudio, memorización rápida y aprendizaje productivo","url":"https://www.youtube.com/watch?v=_HmFAEPeBCs","url_en":"https://www.youtube.com/watch?v=_HmFAEPeBCs","duracion":"10 min"}]'::jsonb
WHERE id = 'e0722730-85dc-4383-a269-e8f7cf78ed9d';

UPDATE semanas SET videos = '[{"titulo":"Conversiones Super facil - Conversiones para principiantes","titulo_en":"Conversiones Super facil - Conversiones para principiantes","url":"https://www.youtube.com/watch?v=T3hc4N6YjJg","url_en":"https://www.youtube.com/watch?v=T3hc4N6YjJg","duracion":"10 min"},{"titulo":"CONVERTIR DECIMAL PERIODICO A FRACCIÓN Super fácil - Para principiantes","titulo_en":"CONVERTIR DECIMAL PERIODICO A FRACCIÓN Super fácil - Para principiantes","url":"https://www.youtube.com/watch?v=1JJgHZg9CeE","url_en":"https://www.youtube.com/watch?v=1JJgHZg9CeE","duracion":"10 min"},{"titulo":"Conversión de números decimales a fracciones y viceversa","titulo_en":"Conversión de números decimales a fracciones y viceversa","url":"https://www.youtube.com/watch?v=4EdwMeNBRO0","url_en":"https://www.youtube.com/watch?v=4EdwMeNBRO0","duracion":"10 min"}]'::jsonb
WHERE id = '89c22fca-746b-43f4-9ebb-798d86568257';

UPDATE semanas SET videos = '[{"titulo":"Verbos Irregulares en inglés - Cómo aprender rápido","titulo_en":"Verbos Irregulares en inglés - Cómo aprender rápido","url":"https://www.youtube.com/watch?v=iBNDChyqMrs","url_en":"https://www.youtube.com/watch?v=iBNDChyqMrs","duracion":"10 min"},{"titulo":"PASADO SIMPLE EN INGLÉS: ¡domínalo de una vez por todas!","titulo_en":"PASADO SIMPLE EN INGLÉS: ¡domínalo de una vez por todas!","url":"https://www.youtube.com/watch?v=F8aEosp-bFk","url_en":"https://www.youtube.com/watch?v=F8aEosp-bFk","duracion":"10 min"},{"titulo":"INGLÉS BÁSICO: EL PASADO | Superholly","titulo_en":"INGLÉS BÁSICO: EL PASADO | Superholly","url":"https://www.youtube.com/watch?v=GcTSbETuREw","url_en":"https://www.youtube.com/watch?v=GcTSbETuREw","duracion":"10 min"}]'::jsonb
WHERE id = 'd9d1d0b8-1e15-44c1-bb61-04e32af35cb0';

UPDATE semanas SET videos = '[{"titulo":"IDENTIFICA EL TEMA, LA IDEA PRINCIPAL Y SECUNDARIAS DE UN TEXTO PASO A PASO","titulo_en":"IDENTIFICA EL TEMA, LA IDEA PRINCIPAL Y SECUNDARIAS DE UN TEXTO PASO A PASO","url":"https://www.youtube.com/watch?v=iR0-03DZJGI","url_en":"https://www.youtube.com/watch?v=iR0-03DZJGI","duracion":"10 min"},{"titulo":"💡 Cómo Encontrar las Ideas Principales de un Texto (Guía Completa) | Curso de Lectura #11","titulo_en":"💡 Cómo Encontrar las Ideas Principales de un Texto (Guía Completa) | Curso de Lectura #11","url":"https://www.youtube.com/watch?v=4v6-sU7QJ_w","url_en":"https://www.youtube.com/watch?v=4v6-sU7QJ_w","duracion":"10 min"},{"titulo":"ESTRUCTURA DEL TEXTO :TEMA, TÍTULO, IDEA PRINCIPAL E IDEAS SECUNDARIAS","titulo_en":"ESTRUCTURA DEL TEXTO :TEMA, TÍTULO, IDEA PRINCIPAL E IDEAS SECUNDARIAS","url":"https://www.youtube.com/watch?v=BXARzIXuSso","url_en":"https://www.youtube.com/watch?v=BXARzIXuSso","duracion":"10 min"}]'::jsonb
WHERE id = 'bfa10dba-13b7-4af5-a43e-539ac600f6e6';

UPDATE semanas SET videos = '[{"titulo":"La Civilización MAYA - Resumen | Origen, política, sociedad, economía, religión, arquitectura...","titulo_en":"La Civilización MAYA - Resumen | Origen, política, sociedad, economía, religión, arquitectura...","url":"https://www.youtube.com/watch?v=J-3n1FFH6LQ","url_en":"https://www.youtube.com/watch?v=J-3n1FFH6LQ","duracion":"10 min"},{"titulo":"El LIBERALISMO - Resumen | Liberalismo Político y Liberalismo Económico","titulo_en":"El LIBERALISMO - Resumen | Liberalismo Político y Liberalismo Económico","url":"https://www.youtube.com/watch?v=ogzcw7xolZg","url_en":"https://www.youtube.com/watch?v=ogzcw7xolZg","duracion":"10 min"},{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"}]'::jsonb
WHERE id = '21b99e99-d12d-4306-a3dc-23659996d021';

UPDATE semanas SET videos = '[{"titulo":"LENGUAJE ALGEBRAICO Superfácil - Para principiantes PARTE 1","titulo_en":"LENGUAJE ALGEBRAICO Superfácil - Para principiantes PARTE 1","url":"https://www.youtube.com/watch?v=UNWFLuUfiX4","url_en":"https://www.youtube.com/watch?v=UNWFLuUfiX4","duracion":"10 min"},{"titulo":"SUMA DE EXPRESIONES ALGEBRAICAS Super facil - Para principiantes","titulo_en":"SUMA DE EXPRESIONES ALGEBRAICAS Super facil - Para principiantes","url":"https://www.youtube.com/watch?v=UJiUu8-fYgI","url_en":"https://www.youtube.com/watch?v=UJiUu8-fYgI","duracion":"10 min"},{"titulo":"Lenguaje algebraico | Parte 1","titulo_en":"Lenguaje algebraico | Parte 1","url":"https://www.youtube.com/watch?v=DV3C_RawfBg","url_en":"https://www.youtube.com/watch?v=DV3C_RawfBg","duracion":"10 min"}]'::jsonb
WHERE id = 'd498879e-4394-4470-8154-6b9a550a7657';

UPDATE semanas SET videos = '[{"titulo":"Salud Sexual y Reproductiva","titulo_en":"Salud Sexual y Reproductiva","url":"https://www.youtube.com/watch?v=F1WrfWtsdRY","url_en":"https://www.youtube.com/watch?v=F1WrfWtsdRY","duracion":"10 min"},{"titulo":"💊TODO lo que debes saber sobre los métodos anticonceptivos | Reina Madre","titulo_en":"💊TODO lo que debes saber sobre los métodos anticonceptivos | Reina Madre","url":"https://www.youtube.com/watch?v=2Sv20zNo5n8","url_en":"https://www.youtube.com/watch?v=2Sv20zNo5n8","duracion":"10 min"},{"titulo":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","titulo_en":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","url":"https://www.youtube.com/watch?v=F6_QXn0GcdI","url_en":"https://www.youtube.com/watch?v=F6_QXn0GcdI","duracion":"10 min"}]'::jsonb
WHERE id = '519b2f0d-8866-42a5-a868-7b72b16b3de1';

UPDATE semanas SET videos = '[{"titulo":"Hábitos para gestionar tu tiempo - ¿Cómo planificar el tiempo?","titulo_en":"Hábitos para gestionar tu tiempo - ¿Cómo planificar el tiempo?","url":"https://www.youtube.com/watch?v=YiFHl6em4WE","url_en":"https://www.youtube.com/watch?v=YiFHl6em4WE","duracion":"10 min"},{"titulo":"FUNCIONES del DEPARTAMENTO de RECURSOS HUMANOS 👦 | Economía de la empresa 148#","titulo_en":"FUNCIONES del DEPARTAMENTO de RECURSOS HUMANOS 👦 | Economía de la empresa 148#","url":"https://www.youtube.com/watch?v=AcSI9FsUW4A","url_en":"https://www.youtube.com/watch?v=AcSI9FsUW4A","duracion":"10 min"},{"titulo":"Gestión de Proyectos | Metodología PMI (Ejemplo Práctico)","titulo_en":"Gestión de Proyectos | Metodología PMI (Ejemplo Práctico)","url":"https://www.youtube.com/watch?v=Og7iI31kwPQ","url_en":"https://www.youtube.com/watch?v=Og7iI31kwPQ","duracion":"10 min"}]'::jsonb
WHERE id = '7ec0b567-eb65-4d0c-98fb-6727a1fb9384';

UPDATE semanas SET videos = '[{"titulo":"RESOLVER SISTEMAS DE ECUACIONES MÉTODO DE SUSTITUCIÓN Super fácil - Para principiantes","titulo_en":"RESOLVER SISTEMAS DE ECUACIONES MÉTODO DE SUSTITUCIÓN Super fácil - Para principiantes","url":"https://www.youtube.com/watch?v=L0QuX9RpEoM","url_en":"https://www.youtube.com/watch?v=L0QuX9RpEoM","duracion":"10 min"},{"titulo":"Sistemas de ecuaciones lineales 2x2 | Método de Sustitución | Ejemplo 1","titulo_en":"Sistemas de ecuaciones lineales 2x2 | Método de Sustitución | Ejemplo 1","url":"https://www.youtube.com/watch?v=LTfv1G2iYuQ","url_en":"https://www.youtube.com/watch?v=LTfv1G2iYuQ","duracion":"10 min"},{"titulo":"Sistemas de dos ecuaciones con dos incógnitas. Todosobresaliente.com","titulo_en":"Sistemas de dos ecuaciones con dos incógnitas. Todosobresaliente.com","url":"https://www.youtube.com/watch?v=k8NEpHKFAnY","url_en":"https://www.youtube.com/watch?v=k8NEpHKFAnY","duracion":"10 min"}]'::jsonb
WHERE id = 'bf689d51-e5cd-40b5-8ce0-648d6d537fe7';

UPDATE semanas SET videos = '[{"titulo":"¿Cómo acentuar? - AGUDAS, GRAVES, ESDRÚJULAS, SOBREESDRÚJULAS, SÍLABA TÓNICA, SÍLABA ÁTONA","titulo_en":"¿Cómo acentuar? - AGUDAS, GRAVES, ESDRÚJULAS, SOBREESDRÚJULAS, SÍLABA TÓNICA, SÍLABA ÁTONA","url":"https://www.youtube.com/watch?v=dfzlBAMVrBI","url_en":"https://www.youtube.com/watch?v=dfzlBAMVrBI","duracion":"10 min"},{"titulo":"📜REGLAS de ACENTUACIÓN o TILDACIÓN para NIÑOS de PRIMARIA 🖋️ [AGUDAS, LLANAS o graves y ESDRÚJULAS]","titulo_en":"📜REGLAS de ACENTUACIÓN o TILDACIÓN para NIÑOS de PRIMARIA 🖋️ [AGUDAS, LLANAS o graves y ESDRÚJULAS]","url":"https://www.youtube.com/watch?v=69KYr9BaiYA","url_en":"https://www.youtube.com/watch?v=69KYr9BaiYA","duracion":"10 min"},{"titulo":"REGLAS de ACENTUACIÓN 📏 Palabras Agudas, Llanas, Esdrújulas y Sobreesdrújulas","titulo_en":"REGLAS de ACENTUACIÓN 📏 Palabras Agudas, Llanas, Esdrújulas y Sobreesdrújulas","url":"https://www.youtube.com/watch?v=3Qzip92Rrpg","url_en":"https://www.youtube.com/watch?v=3Qzip92Rrpg","duracion":"10 min"}]'::jsonb
WHERE id = 'ab966df6-1c1e-4994-8604-36e0ea3c7cf4';

UPDATE semanas SET videos = '[{"titulo":"Elementos del texto argumentativo: Tesis, argumentación y conclusión","titulo_en":"Elementos del texto argumentativo: Tesis, argumentación y conclusión","url":"https://www.youtube.com/watch?v=BPeF4art-00","url_en":"https://www.youtube.com/watch?v=BPeF4art-00","duracion":"10 min"},{"titulo":"📚 TEXTO ARGUMENTATIVO | Características, contenidos, clases y rasgos lingüísticos","titulo_en":"📚 TEXTO ARGUMENTATIVO | Características, contenidos, clases y rasgos lingüísticos","url":"https://www.youtube.com/watch?v=Mq4Hzx1peNU","url_en":"https://www.youtube.com/watch?v=Mq4Hzx1peNU","duracion":"10 min"},{"titulo":"TEXTOS ARGUMENTATIVOS","titulo_en":"TEXTOS ARGUMENTATIVOS","url":"https://www.youtube.com/watch?v=wjncoldGiiY","url_en":"https://www.youtube.com/watch?v=wjncoldGiiY","duracion":"10 min"}]'::jsonb
WHERE id = 'a3e91941-922e-430e-a571-e3566f8c43e1';

UPDATE semanas SET videos = '[{"titulo":"Hábitos Saludables - salud física y mental | Aula chachi - Vídeos educativos para niños","titulo_en":"Hábitos Saludables - salud física y mental | Aula chachi - Vídeos educativos para niños","url":"https://www.youtube.com/watch?v=qhwyGwNj06E","url_en":"https://www.youtube.com/watch?v=qhwyGwNj06E","duracion":"10 min"},{"titulo":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","titulo_en":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","url":"https://www.youtube.com/watch?v=YWGOThGG8-Y","url_en":"https://www.youtube.com/watch?v=YWGOThGG8-Y","duracion":"10 min"},{"titulo":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","titulo_en":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","url":"https://www.youtube.com/watch?v=qHimbDfTXYg","url_en":"https://www.youtube.com/watch?v=qHimbDfTXYg","duracion":"10 min"}]'::jsonb
WHERE id = 'ff53dd98-22f6-43ed-9f97-75cfde1a615f';

UPDATE semanas SET videos = '[{"titulo":"Los FUTUROS en INGLÉS | Will - Be Going to - P. Continuo - P. Simple | Gramática","titulo_en":"Los FUTUROS en INGLÉS | Will - Be Going to - P. Continuo - P. Simple | Gramática","url":"https://www.youtube.com/watch?v=XACvspcClW0","url_en":"https://www.youtube.com/watch?v=XACvspcClW0","duracion":"10 min"},{"titulo":"WILL vs. GOING TO - DIFERENCIAS - FUTURO EN INGLES","titulo_en":"WILL vs. GOING TO - DIFERENCIAS - FUTURO EN INGLES","url":"https://www.youtube.com/watch?v=P5NFYbzr2xI","url_en":"https://www.youtube.com/watch?v=P5NFYbzr2xI","duracion":"10 min"},{"titulo":"Cómo Usar el Futuro GOING TO en INGLÉS MUY FÁCIL 🤗| Explicación en español 📚","titulo_en":"Cómo Usar el Futuro GOING TO en INGLÉS MUY FÁCIL 🤗| Explicación en español 📚","url":"https://www.youtube.com/watch?v=KYZeeT5MdFA","url_en":"https://www.youtube.com/watch?v=KYZeeT5MdFA","duracion":"10 min"}]'::jsonb
WHERE id = '03491332-6c25-43f6-a372-5eecf0fd5f7a';

UPDATE semanas SET videos = '[{"titulo":"Cómo usar Google Docs - Editor de Documentos de Google 2025","titulo_en":"Cómo usar Google Docs - Editor de Documentos de Google 2025","url":"https://www.youtube.com/watch?v=xApZhkNcJyY","url_en":"https://www.youtube.com/watch?v=xApZhkNcJyY","duracion":"10 min"},{"titulo":"🏆 Actividad integradora 2 Módulo 01. 🔹 WORD 🔹 PARTE 1 --  ⭐️ Prepa en línea SEP ⭐️","titulo_en":"🏆 Actividad integradora 2 Módulo 01. 🔹 WORD 🔹 PARTE 1 --  ⭐️ Prepa en línea SEP ⭐️","url":"https://www.youtube.com/watch?v=v5GDwHI8Wyw","url_en":"https://www.youtube.com/watch?v=v5GDwHI8Wyw","duracion":"10 min"},{"titulo":"CÓMO HACER UN INFORME EN WORD ✅ REDACTAR UN INFORME CORRECTAMENTE📑 EN 5 MINUTOS✨","titulo_en":"CÓMO HACER UN INFORME EN WORD ✅ REDACTAR UN INFORME CORRECTAMENTE📑 EN 5 MINUTOS✨","url":"https://www.youtube.com/watch?v=zy9hyWjf29w","url_en":"https://www.youtube.com/watch?v=zy9hyWjf29w","duracion":"10 min"}]'::jsonb
WHERE id = '56dad3dc-78bd-48f4-9929-9d8c5efe92d3';

UPDATE semanas SET videos = '[{"titulo":"🔴 ¿ Qué es un DIAGRAMA DE FLUJO ? 🔼 Cómo HACER Diagramas de Flujo Paso a Paso + Ejemplos","titulo_en":"🔴 ¿ Qué es un DIAGRAMA DE FLUJO ? 🔼 Cómo HACER Diagramas de Flujo Paso a Paso + Ejemplos","url":"https://www.youtube.com/watch?v=Kucgc6NpGwc","url_en":"https://www.youtube.com/watch?v=Kucgc6NpGwc","duracion":"10 min"},{"titulo":"Aprende PYTHON en 10 minutos 🟢","titulo_en":"Aprende PYTHON en 10 minutos 🟢","url":"https://www.youtube.com/watch?v=_6N18g3ewnw","url_en":"https://www.youtube.com/watch?v=_6N18g3ewnw","duracion":"10 min"},{"titulo":"Curso de Programación en PSEINT [#10] - Ciclo MIENTRAS (Bucle While)","titulo_en":"Curso de Programación en PSEINT [#10] - Ciclo MIENTRAS (Bucle While)","url":"https://www.youtube.com/watch?v=Cea0bywr7-w","url_en":"https://www.youtube.com/watch?v=Cea0bywr7-w","duracion":"10 min"}]'::jsonb
WHERE id = '67645733-03da-434d-b4cb-9f197ea3d5b8';

UPDATE semanas SET videos = '[{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"}]'::jsonb
WHERE id = '74cdcbee-f875-471a-8392-38002bef140f';

UPDATE semanas SET videos = '[{"titulo":"SINGULAR Y PLURAL EN INGLÉS","titulo_en":"SINGULAR Y PLURAL EN INGLÉS","url":"https://www.youtube.com/watch?v=QWvx1czzG4Y","url_en":"https://www.youtube.com/watch?v=QWvx1czzG4Y","duracion":"10 min"},{"titulo":"Sustantivos Plurales y Singulares en Ingles - Ejercicios - Reglas Plurales -  Lección # 16","titulo_en":"Sustantivos Plurales y Singulares en Ingles - Ejercicios - Reglas Plurales -  Lección # 16","url":"https://www.youtube.com/watch?v=a-oLUsdOwWs","url_en":"https://www.youtube.com/watch?v=a-oLUsdOwWs","duracion":"10 min"},{"titulo":"Sustantivos contables y no contables en inglés. Countable and uncountable nouns.","titulo_en":"Sustantivos contables y no contables en inglés. Countable and uncountable nouns.","url":"https://www.youtube.com/watch?v=rYLM2xM3ybM","url_en":"https://www.youtube.com/watch?v=rYLM2xM3ybM","duracion":"10 min"}]'::jsonb
WHERE id = '97168b14-4628-4650-8e54-2f924637e551';

UPDATE semanas SET videos = '[{"titulo":"ECUACIONES DE PRIMER GRADO | Superfácil | Para principiantes","titulo_en":"ECUACIONES DE PRIMER GRADO | Superfácil | Para principiantes","url":"https://www.youtube.com/watch?v=IHblqjW8RY8","url_en":"https://www.youtube.com/watch?v=IHblqjW8RY8","duracion":"10 min"},{"titulo":"ECUACIONES LINEALES Super facil para principiantes","titulo_en":"ECUACIONES LINEALES Super facil para principiantes","url":"https://www.youtube.com/watch?v=8rT0DZbYGEs","url_en":"https://www.youtube.com/watch?v=8rT0DZbYGEs","duracion":"10 min"},{"titulo":"LENGUAJE ALGEBRAICO Superfácil - Para principiantes PARTE 1","titulo_en":"LENGUAJE ALGEBRAICO Superfácil - Para principiantes PARTE 1","url":"https://www.youtube.com/watch?v=UNWFLuUfiX4","url_en":"https://www.youtube.com/watch?v=UNWFLuUfiX4","duracion":"10 min"}]'::jsonb
WHERE id = 'fff9308e-29fc-4d4e-a93d-450a47fe8085';

UPDATE semanas SET videos = '[{"titulo":"¿Cómo empezar a Cuidar mi Salud Mental?","titulo_en":"¿Cómo empezar a Cuidar mi Salud Mental?","url":"https://www.youtube.com/watch?v=wfOHdfqqJTs","url_en":"https://www.youtube.com/watch?v=wfOHdfqqJTs","duracion":"10 min"},{"titulo":"Salud mental, la clase que nadie nos dió | Fernando Lemarroy | TEDxTecdeMty","titulo_en":"Salud mental, la clase que nadie nos dió | Fernando Lemarroy | TEDxTecdeMty","url":"https://www.youtube.com/watch?v=_9agX3gY1jU","url_en":"https://www.youtube.com/watch?v=_9agX3gY1jU","duracion":"10 min"},{"titulo":"Un Trip de Salud Mental | Casi Creativo","titulo_en":"Un Trip de Salud Mental | Casi Creativo","url":"https://www.youtube.com/watch?v=JQr6Ld8d-f8","url_en":"https://www.youtube.com/watch?v=JQr6Ld8d-f8","duracion":"10 min"}]'::jsonb
WHERE id = '5d71530d-4e10-483a-827c-c4ca46137492';

UPDATE semanas SET videos = '[{"titulo":"¿Qué son las TIC y para qué sirven? Tipos y ejemplos (Tecnologías de la Información y Comunicación)","titulo_en":"¿Qué son las TIC y para qué sirven? Tipos y ejemplos (Tecnologías de la Información y Comunicación)","url":"https://www.youtube.com/watch?v=q8MeNBwRtPU","url_en":"https://www.youtube.com/watch?v=q8MeNBwRtPU","duracion":"10 min"},{"titulo":"¿Qué es Marketing Digital? Introducción, Tipos y Canales","titulo_en":"¿Qué es Marketing Digital? Introducción, Tipos y Canales","url":"https://www.youtube.com/watch?v=nACJLWCmzk8","url_en":"https://www.youtube.com/watch?v=nACJLWCmzk8","duracion":"10 min"},{"titulo":"Cómo hacer una buena presentación visual (Diapositivas)","titulo_en":"Cómo hacer una buena presentación visual (Diapositivas)","url":"https://www.youtube.com/watch?v=bUHR7lYepT0","url_en":"https://www.youtube.com/watch?v=bUHR7lYepT0","duracion":"10 min"}]'::jsonb
WHERE id = '0f9c4eaa-a0fd-4cde-a727-14c9b5e06c81';

UPDATE semanas SET videos = '[{"titulo":"Salud Sexual y Reproductiva","titulo_en":"Salud Sexual y Reproductiva","url":"https://www.youtube.com/watch?v=F1WrfWtsdRY","url_en":"https://www.youtube.com/watch?v=F1WrfWtsdRY","duracion":"10 min"},{"titulo":"Derechos sexuales y reproductivos, salud y género","titulo_en":"Derechos sexuales y reproductivos, salud y género","url":"https://www.youtube.com/watch?v=L_3oEtlUjE4","url_en":"https://www.youtube.com/watch?v=L_3oEtlUjE4","duracion":"10 min"},{"titulo":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","titulo_en":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","url":"https://www.youtube.com/watch?v=F6_QXn0GcdI","url_en":"https://www.youtube.com/watch?v=F6_QXn0GcdI","duracion":"10 min"}]'::jsonb
WHERE id = '337f93c7-c7bc-4173-98c4-ce5f6bbf3c3d';

UPDATE semanas SET videos = '[{"titulo":"🔴 SIGNOS de PUNTUACIÓN 🔴 Cómo se USAN y EJEMPLOS para NIÑOS","titulo_en":"🔴 SIGNOS de PUNTUACIÓN 🔴 Cómo se USAN y EJEMPLOS para NIÑOS","url":"https://www.youtube.com/watch?v=2Bs6tknaLJQ","url_en":"https://www.youtube.com/watch?v=2Bs6tknaLJQ","duracion":"10 min"},{"titulo":"📚SIGNOS DE PUNTUACIÓN👉 Cómo se usan y ejemplos 📌Video educativo","titulo_en":"📚SIGNOS DE PUNTUACIÓN👉 Cómo se usan y ejemplos 📌Video educativo","url":"https://www.youtube.com/watch?v=bUJhBIfcHgs","url_en":"https://www.youtube.com/watch?v=bUJhBIfcHgs","duracion":"10 min"},{"titulo":"Signos de puntuación","titulo_en":"Signos de puntuación","url":"https://www.youtube.com/watch?v=Zx2Cf_gNu_I","url_en":"https://www.youtube.com/watch?v=Zx2Cf_gNu_I","duracion":"10 min"}]'::jsonb
WHERE id = 'dfd86690-196b-435a-b15c-dc24add54f49';

UPDATE semanas SET videos = '[{"titulo":"Intervalos introducción | tipos de intervalos","titulo_en":"Intervalos introducción | tipos de intervalos","url":"https://www.youtube.com/watch?v=yhdmoH_lyeU","url_en":"https://www.youtube.com/watch?v=yhdmoH_lyeU","duracion":"10 min"},{"titulo":"Desigualdades &quot;Intervalos&quot;","titulo_en":"Desigualdades &quot;Intervalos&quot;","url":"https://www.youtube.com/watch?v=bHOIfF5-Rak","url_en":"https://www.youtube.com/watch?v=bHOIfF5-Rak","duracion":"10 min"},{"titulo":"Ejercicios con INTERVALOS 🟧 Expresar como Desigualdad, Intervalo y Representación en Recta Numérica","titulo_en":"Ejercicios con INTERVALOS 🟧 Expresar como Desigualdad, Intervalo y Representación en Recta Numérica","url":"https://www.youtube.com/watch?v=PmWyGkQ1gtg","url_en":"https://www.youtube.com/watch?v=PmWyGkQ1gtg","duracion":"10 min"}]'::jsonb
WHERE id = '3cfafb80-615f-4ec6-bedf-22ddb6b917b8';

UPDATE semanas SET videos = '[{"titulo":"CONSEJOS PARA PROFESORES NOVATOS: No cometas estos ERRORES ¡Lo digo por experiencia!|Primeras clases","titulo_en":"CONSEJOS PARA PROFESORES NOVATOS: No cometas estos ERRORES ¡Lo digo por experiencia!|Primeras clases","url":"https://www.youtube.com/watch?v=4gf8MRtB5BQ","url_en":"https://www.youtube.com/watch?v=4gf8MRtB5BQ","duracion":"10 min"},{"titulo":"¿Cómo MEJORAR tu manera de Estudiar? | Drpologuerrero","titulo_en":"¿Cómo MEJORAR tu manera de Estudiar? | Drpologuerrero","url":"https://www.youtube.com/watch?v=MAjm9Sfc9Mg","url_en":"https://www.youtube.com/watch?v=MAjm9Sfc9Mg","duracion":"10 min"},{"titulo":"¿Cuáles son los retos de la educación del siglo XXI? César Coll, catedrático de Psicología Evolutiva","titulo_en":"¿Cuáles son los retos de la educación del siglo XXI? César Coll, catedrático de Psicología Evolutiva","url":"https://www.youtube.com/watch?v=OLKWN8yYECY","url_en":"https://www.youtube.com/watch?v=OLKWN8yYECY","duracion":"10 min"}]'::jsonb
WHERE id = '3ae2827b-2fb2-4a26-a134-3c912b8ffedf';

UPDATE semanas SET videos = '[{"titulo":"Presente Simple en Ingles - Simple Present Tense – Oraciones y Ejercicios | Lección # 6","titulo_en":"Presente Simple en Ingles - Simple Present Tense – Oraciones y Ejercicios | Lección # 6","url":"https://www.youtube.com/watch?v=sfjUz-Oyq5E","url_en":"https://www.youtube.com/watch?v=sfjUz-Oyq5E","duracion":"10 min"},{"titulo":"EL PRESENTE SIMPLE EN INGLES - REGLAS (S - ES - IES) - EXPLICACION SENCILLA","titulo_en":"EL PRESENTE SIMPLE EN INGLES - REGLAS (S - ES - IES) - EXPLICACION SENCILLA","url":"https://www.youtube.com/watch?v=o8xOJPKfraU","url_en":"https://www.youtube.com/watch?v=o8xOJPKfraU","duracion":"10 min"},{"titulo":"PRESENT SIMPLE   INGLÉS PARA NIÑOS CON MR  PEA   ENGLISH FOR KIDS","titulo_en":"PRESENT SIMPLE   INGLÉS PARA NIÑOS CON MR  PEA   ENGLISH FOR KIDS","url":"https://www.youtube.com/watch?v=wtTAdfyejH0","url_en":"https://www.youtube.com/watch?v=wtTAdfyejH0","duracion":"10 min"}]'::jsonb
WHERE id = '9e6e7df2-f44f-4f35-9ce8-575342bd61a8';

UPDATE semanas SET videos = '[{"titulo":"​🔵​Qué son las FIGURAS LITERARIAS y ejemplos (parte 1) | Cuáles son las figuras literarias","titulo_en":"​🔵​Qué son las FIGURAS LITERARIAS y ejemplos (parte 1) | Cuáles son las figuras literarias","url":"https://www.youtube.com/watch?v=SlmBEJx-mXU","url_en":"https://www.youtube.com/watch?v=SlmBEJx-mXU","duracion":"10 min"},{"titulo":"Figuras literarias explicadas con ejemplos✍","titulo_en":"Figuras literarias explicadas con ejemplos✍","url":"https://www.youtube.com/watch?v=xeVfyy9UP5E","url_en":"https://www.youtube.com/watch?v=xeVfyy9UP5E","duracion":"10 min"},{"titulo":"FIGURAS LITERARIAS para niños 🧾​ Símil, metáfora e hipérbole ✏️​ Literatura para niños ✍️ Episodio 1","titulo_en":"FIGURAS LITERARIAS para niños 🧾​ Símil, metáfora e hipérbole ✏️​ Literatura para niños ✍️ Episodio 1","url":"https://www.youtube.com/watch?v=vunzhUk5hsg","url_en":"https://www.youtube.com/watch?v=vunzhUk5hsg","duracion":"10 min"}]'::jsonb
WHERE id = '861615e1-2b0d-4592-a1b0-c60b9fdfbe20';

UPDATE semanas SET videos = '[{"titulo":"Curso de Programación en PSEINT [#10] - Ciclo MIENTRAS (Bucle While)","titulo_en":"Curso de Programación en PSEINT [#10] - Ciclo MIENTRAS (Bucle While)","url":"https://www.youtube.com/watch?v=Cea0bywr7-w","url_en":"https://www.youtube.com/watch?v=Cea0bywr7-w","duracion":"10 min"},{"titulo":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","titulo_en":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","url":"https://www.youtube.com/watch?v=as1opL254NA","url_en":"https://www.youtube.com/watch?v=as1opL254NA","duracion":"10 min"},{"titulo":"Aprende PYTHON en 10 minutos 🟢","titulo_en":"Aprende PYTHON en 10 minutos 🟢","url":"https://www.youtube.com/watch?v=_6N18g3ewnw","url_en":"https://www.youtube.com/watch?v=_6N18g3ewnw","duracion":"10 min"}]'::jsonb
WHERE id = 'c53c7db7-98e2-4f6d-a0e9-62549f7ba958';

UPDATE semanas SET videos = '[{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"},{"titulo":"La Civilización MAYA - Resumen | Origen, política, sociedad, economía, religión, arquitectura...","titulo_en":"La Civilización MAYA - Resumen | Origen, política, sociedad, economía, religión, arquitectura...","url":"https://www.youtube.com/watch?v=J-3n1FFH6LQ","url_en":"https://www.youtube.com/watch?v=J-3n1FFH6LQ","duracion":"10 min"},{"titulo":"HISTORIA - Origen y Evolución del Español o Castellano | MINI-DOCUMENTAL","titulo_en":"HISTORIA - Origen y Evolución del Español o Castellano | MINI-DOCUMENTAL","url":"https://www.youtube.com/watch?v=ZpAdq8sb5iI","url_en":"https://www.youtube.com/watch?v=ZpAdq8sb5iI","duracion":"10 min"}]'::jsonb
WHERE id = '69ab9f20-8142-4cc6-ad0e-4135569b6ae0';

UPDATE semanas SET videos = '[{"titulo":"Modal Verbs - MUST, HAVE TO, SHOULD, OUGHT TO, HAD BETTER, NEED- Explicación, ejemplos, ejercicios.","titulo_en":"Modal Verbs - MUST, HAVE TO, SHOULD, OUGHT TO, HAD BETTER, NEED- Explicación, ejemplos, ejercicios.","url":"https://www.youtube.com/watch?v=Xhd1bEVXoZk","url_en":"https://www.youtube.com/watch?v=Xhd1bEVXoZk","duracion":"10 min"},{"titulo":"VERBOS MODALES de deducción en inglés : MUST, CAN&#39;T, COULD , MAY , MIGHT","titulo_en":"VERBOS MODALES de deducción en inglés : MUST, CAN&#39;T, COULD , MAY , MIGHT","url":"https://www.youtube.com/watch?v=rrzjOeh_9TI","url_en":"https://www.youtube.com/watch?v=rrzjOeh_9TI","duracion":"10 min"},{"titulo":"Modal Verbs Would, Could, Should, Must, May, Might, Can,  en español","titulo_en":"Modal Verbs Would, Could, Should, Must, May, Might, Can,  en español","url":"https://www.youtube.com/watch?v=2LhuE7BnL4g","url_en":"https://www.youtube.com/watch?v=2LhuE7BnL4g","duracion":"10 min"}]'::jsonb
WHERE id = 'ad6eaf5c-86f8-4de0-a780-835364e39267';

UPDATE semanas SET videos = '[{"titulo":"¿Ves lo que yo? (Cortometraje sobre violencia de género)","titulo_en":"¿Ves lo que yo? (Cortometraje sobre violencia de género)","url":"https://www.youtube.com/watch?v=Id0KeN49jHY","url_en":"https://www.youtube.com/watch?v=Id0KeN49jHY","duracion":"10 min"},{"titulo":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","titulo_en":"¿Cómo hablar de sexualidad con niños y adolescentes? | Tu Salud Guía","url":"https://www.youtube.com/watch?v=F6_QXn0GcdI","url_en":"https://www.youtube.com/watch?v=F6_QXn0GcdI","duracion":"10 min"},{"titulo":"Yo respeto, tú respetas - Cortometraje de reflexión","titulo_en":"Yo respeto, tú respetas - Cortometraje de reflexión","url":"https://www.youtube.com/watch?v=DBcMCo0eArg","url_en":"https://www.youtube.com/watch?v=DBcMCo0eArg","duracion":"10 min"}]'::jsonb
WHERE id = '96ec18c4-ecb2-4468-9168-3b9097cb5c70';

UPDATE semanas SET videos = '[{"titulo":"Aprende La Ropa en Inglés | Clothes Vocabulary","titulo_en":"Aprende La Ropa en Inglés | Clothes Vocabulary","url":"https://www.youtube.com/watch?v=2eNk6zKidrU","url_en":"https://www.youtube.com/watch?v=2eNk6zKidrU","duracion":"10 min"},{"titulo":"Diferencia entre PRESENTE SIMPLE y PRESENTE CONTINUO en inglés","titulo_en":"Diferencia entre PRESENTE SIMPLE y PRESENTE CONTINUO en inglés","url":"https://www.youtube.com/watch?v=57v-YdOBGTY","url_en":"https://www.youtube.com/watch?v=57v-YdOBGTY","duracion":"10 min"},{"titulo":"Emociones en Inglés | Sentimientos en Inglés Para Niños","titulo_en":"Emociones en Inglés | Sentimientos en Inglés Para Niños","url":"https://www.youtube.com/watch?v=aT9CKFC9D2c","url_en":"https://www.youtube.com/watch?v=aT9CKFC9D2c","duracion":"10 min"}]'::jsonb
WHERE id = 'db305e88-3d80-47ee-8412-56a714b2c425';

UPDATE semanas SET videos = '[{"titulo":"¿Cómo desarrollar el pensamiento crítico?","titulo_en":"¿Cómo desarrollar el pensamiento crítico?","url":"https://www.youtube.com/watch?v=i-htv81L04g","url_en":"https://www.youtube.com/watch?v=i-htv81L04g","duracion":"10 min"},{"titulo":"LECTURA CRÍTICA: ¿Qué es y cómo realizarla? 📖🧠","titulo_en":"LECTURA CRÍTICA: ¿Qué es y cómo realizarla? 📖🧠","url":"https://www.youtube.com/watch?v=qUFACQnfoyQ","url_en":"https://www.youtube.com/watch?v=qUFACQnfoyQ","duracion":"10 min"},{"titulo":"¿Qué es la LECTURA CRÍTICA y cuáles son sus características? (Con ejemplos)📖","titulo_en":"¿Qué es la LECTURA CRÍTICA y cuáles son sus características? (Con ejemplos)📖","url":"https://www.youtube.com/watch?v=Gc0LVdAW9c8","url_en":"https://www.youtube.com/watch?v=Gc0LVdAW9c8","duracion":"10 min"}]'::jsonb
WHERE id = '331b617c-59a0-4de9-ae7f-da72fdb234ab';

UPDATE semanas SET videos = '[{"titulo":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","titulo_en":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","url":"https://www.youtube.com/watch?v=as1opL254NA","url_en":"https://www.youtube.com/watch?v=as1opL254NA","duracion":"10 min"},{"titulo":"INTRODUCCIÓN A ALGORITMOS - Ideas y conceptos básicos","titulo_en":"INTRODUCCIÓN A ALGORITMOS - Ideas y conceptos básicos","url":"https://www.youtube.com/watch?v=f10jKIslSUY","url_en":"https://www.youtube.com/watch?v=f10jKIslSUY","duracion":"10 min"},{"titulo":"🔴 ¿ Qué es un DIAGRAMA DE FLUJO ? 🔼 Cómo HACER Diagramas de Flujo Paso a Paso + Ejemplos","titulo_en":"🔴 ¿ Qué es un DIAGRAMA DE FLUJO ? 🔼 Cómo HACER Diagramas de Flujo Paso a Paso + Ejemplos","url":"https://www.youtube.com/watch?v=Kucgc6NpGwc","url_en":"https://www.youtube.com/watch?v=Kucgc6NpGwc","duracion":"10 min"}]'::jsonb
WHERE id = 'ded54196-ea5b-422f-a790-472b8e9d9890';

UPDATE semanas SET videos = '[{"titulo":"Hábitos Saludables - salud física y mental | Aula chachi - Vídeos educativos para niños","titulo_en":"Hábitos Saludables - salud física y mental | Aula chachi - Vídeos educativos para niños","url":"https://www.youtube.com/watch?v=qhwyGwNj06E","url_en":"https://www.youtube.com/watch?v=qhwyGwNj06E","duracion":"10 min"},{"titulo":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","titulo_en":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","url":"https://www.youtube.com/watch?v=YWGOThGG8-Y","url_en":"https://www.youtube.com/watch?v=YWGOThGG8-Y","duracion":"10 min"},{"titulo":"Un Trip de Salud Mental | Casi Creativo","titulo_en":"Un Trip de Salud Mental | Casi Creativo","url":"https://www.youtube.com/watch?v=JQr6Ld8d-f8","url_en":"https://www.youtube.com/watch?v=JQr6Ld8d-f8","duracion":"10 min"}]'::jsonb
WHERE id = 'd6d452dc-715b-47c9-a3f6-29a57877c330';

UPDATE semanas SET videos = '[{"titulo":"Gestión documental, archivo y normatividad   Introducción","titulo_en":"Gestión documental, archivo y normatividad   Introducción","url":"https://www.youtube.com/watch?v=urhSDBpzw6Y","url_en":"https://www.youtube.com/watch?v=urhSDBpzw6Y","duracion":"10 min"},{"titulo":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","titulo_en":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","url":"https://www.youtube.com/watch?v=_JNPvSxG6oM","url_en":"https://www.youtube.com/watch?v=_JNPvSxG6oM","duracion":"10 min"},{"titulo":"Mira TODO lo que PUEDES HACER con GOOGLE DRIVE","titulo_en":"Mira TODO lo que PUEDES HACER con GOOGLE DRIVE","url":"https://www.youtube.com/watch?v=jilQceLFUVE","url_en":"https://www.youtube.com/watch?v=jilQceLFUVE","duracion":"10 min"}]'::jsonb
WHERE id = 'a4acbb34-1b6d-4509-b9c6-778d20e5b3dd';

UPDATE semanas SET videos = '[{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"},{"titulo":"¿Cuáles son los retos de la educación del siglo XXI? César Coll, catedrático de Psicología Evolutiva","titulo_en":"¿Cuáles son los retos de la educación del siglo XXI? César Coll, catedrático de Psicología Evolutiva","url":"https://www.youtube.com/watch?v=OLKWN8yYECY","url_en":"https://www.youtube.com/watch?v=OLKWN8yYECY","duracion":"10 min"},{"titulo":"HISTORIA - Origen y Evolución del Español o Castellano | MINI-DOCUMENTAL","titulo_en":"HISTORIA - Origen y Evolución del Español o Castellano | MINI-DOCUMENTAL","url":"https://www.youtube.com/watch?v=ZpAdq8sb5iI","url_en":"https://www.youtube.com/watch?v=ZpAdq8sb5iI","duracion":"10 min"}]'::jsonb
WHERE id = 'e76b2f04-17e9-4d52-abcb-c88644685be6';

UPDATE semanas SET videos = '[{"titulo":"RESUMEN del PRESENTE SIMPLE-  Afirmativo, negativo e interrogativo","titulo_en":"RESUMEN del PRESENTE SIMPLE-  Afirmativo, negativo e interrogativo","url":"https://www.youtube.com/watch?v=aWbVaxeLtns","url_en":"https://www.youtube.com/watch?v=aWbVaxeLtns","duracion":"10 min"},{"titulo":"EL PRESENTE SIMPLE EN INGLES - REGLAS (S - ES - IES) - EXPLICACION SENCILLA","titulo_en":"EL PRESENTE SIMPLE EN INGLES - REGLAS (S - ES - IES) - EXPLICACION SENCILLA","url":"https://www.youtube.com/watch?v=o8xOJPKfraU","url_en":"https://www.youtube.com/watch?v=o8xOJPKfraU","duracion":"10 min"},{"titulo":"AUXILIARES DO Y DOES. Presente Simple. AFIRMATIVAS NEGATIVAS y PREGUNTAS.","titulo_en":"AUXILIARES DO Y DOES. Presente Simple. AFIRMATIVAS NEGATIVAS y PREGUNTAS.","url":"https://www.youtube.com/watch?v=Vn2-z5cEEVk","url_en":"https://www.youtube.com/watch?v=Vn2-z5cEEVk","duracion":"10 min"}]'::jsonb
WHERE id = '9f821b12-2f84-4871-b16d-5696e7b61aad';

UPDATE semanas SET videos = '[{"titulo":"GRAFICAR FUNCIONES LINEALES PARTE 1","titulo_en":"GRAFICAR FUNCIONES LINEALES PARTE 1","url":"https://www.youtube.com/watch?v=edE5Y1kOgFw","url_en":"https://www.youtube.com/watch?v=edE5Y1kOgFw","duracion":"10 min"},{"titulo":"Gráfica de la función lineal | Ejemplo 1","titulo_en":"Gráfica de la función lineal | Ejemplo 1","url":"https://www.youtube.com/watch?v=AoZpzAoC1Qg","url_en":"https://www.youtube.com/watch?v=AoZpzAoC1Qg","duracion":"10 min"},{"titulo":"ANÁLISIS DE FUNCIONES (Completo)","titulo_en":"ANÁLISIS DE FUNCIONES (Completo)","url":"https://www.youtube.com/watch?v=xb_bdonec6I","url_en":"https://www.youtube.com/watch?v=xb_bdonec6I","duracion":"10 min"}]'::jsonb
WHERE id = '4c009973-76d8-4227-895d-1415ba8d77e2';

UPDATE semanas SET videos = '[{"titulo":"Domina NotebookLM en Menos de 7 Minutos (Tutorial Completo)","titulo_en":"Domina NotebookLM en Menos de 7 Minutos (Tutorial Completo)","url":"https://www.youtube.com/watch?v=Xv5ZrnzA2DA","url_en":"https://www.youtube.com/watch?v=Xv5ZrnzA2DA","duracion":"10 min"},{"titulo":"Técnicas e instrumentos para evaluar los aprendizajes","titulo_en":"Técnicas e instrumentos para evaluar los aprendizajes","url":"https://www.youtube.com/watch?v=bJFMNZl5oqI","url_en":"https://www.youtube.com/watch?v=bJFMNZl5oqI","duracion":"10 min"},{"titulo":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","titulo_en":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","url":"https://www.youtube.com/watch?v=_JNPvSxG6oM","url_en":"https://www.youtube.com/watch?v=_JNPvSxG6oM","duracion":"10 min"}]'::jsonb
WHERE id = 'b62867a1-5715-4106-8631-0942b7c31691';

UPDATE semanas SET videos = '[{"titulo":"RAZONES Y PROPORCIONES Ejercicio 1 Super facil - Para principiantes","titulo_en":"RAZONES Y PROPORCIONES Ejercicio 1 Super facil - Para principiantes","url":"https://www.youtube.com/watch?v=3eYwW4sDlxM","url_en":"https://www.youtube.com/watch?v=3eYwW4sDlxM","duracion":"10 min"},{"titulo":"Razones y proporciones solución de problemas | Ejemplo 1","titulo_en":"Razones y proporciones solución de problemas | Ejemplo 1","url":"https://www.youtube.com/watch?v=jboHWe4_6D8","url_en":"https://www.youtube.com/watch?v=jboHWe4_6D8","duracion":"10 min"},{"titulo":"¿QUÉ SON LAS PROPORCIONES? Super facil - Para principiantes","titulo_en":"¿QUÉ SON LAS PROPORCIONES? Super facil - Para principiantes","url":"https://www.youtube.com/watch?v=8liYyQJ3PIE","url_en":"https://www.youtube.com/watch?v=8liYyQJ3PIE","duracion":"10 min"}]'::jsonb
WHERE id = '95bd1790-0b9d-48d6-a969-8202e123ac10';

UPDATE semanas SET videos = '[{"titulo":"Propiedades del texto: Coherencia y cohesión (Parte 1) :: Lengua y literatura, 1° Bachillerato","titulo_en":"Propiedades del texto: Coherencia y cohesión (Parte 1) :: Lengua y literatura, 1° Bachillerato","url":"https://www.youtube.com/watch?v=NAVDbW1Xl3U","url_en":"https://www.youtube.com/watch?v=NAVDbW1Xl3U","duracion":"10 min"},{"titulo":"📚 PROPIEDADES del TEXTO | ADECUACIÓN, COHERENCIA y COHESIÓN","titulo_en":"📚 PROPIEDADES del TEXTO | ADECUACIÓN, COHERENCIA y COHESIÓN","url":"https://www.youtube.com/watch?v=YdGwL2eJhRQ","url_en":"https://www.youtube.com/watch?v=YdGwL2eJhRQ","duracion":"10 min"},{"titulo":"✅El párrafo | Estructura, Tipos, Características, Función 📝","titulo_en":"✅El párrafo | Estructura, Tipos, Características, Función 📝","url":"https://www.youtube.com/watch?v=NgsQEB43PgA","url_en":"https://www.youtube.com/watch?v=NgsQEB43PgA","duracion":"10 min"}]'::jsonb
WHERE id = '6a12bdb1-8ebf-413a-8ca4-fc9710ff52ec';

UPDATE semanas SET videos = '[{"titulo":"Qué es un plan de acción, características, estructura y ejemplo.","titulo_en":"Qué es un plan de acción, características, estructura y ejemplo.","url":"https://www.youtube.com/watch?v=u5hJEpgQ1iA","url_en":"https://www.youtube.com/watch?v=u5hJEpgQ1iA","duracion":"10 min"},{"titulo":"Gestión de Proyectos | Metodología PMI (Ejemplo Práctico)","titulo_en":"Gestión de Proyectos | Metodología PMI (Ejemplo Práctico)","url":"https://www.youtube.com/watch?v=Og7iI31kwPQ","url_en":"https://www.youtube.com/watch?v=Og7iI31kwPQ","duracion":"10 min"},{"titulo":"Como establecer METAS y OBJETIVOS (Metodo SMART 2022)","titulo_en":"Como establecer METAS y OBJETIVOS (Metodo SMART 2022)","url":"https://www.youtube.com/watch?v=aZhZJaCQnJ4","url_en":"https://www.youtube.com/watch?v=aZhZJaCQnJ4","duracion":"10 min"}]'::jsonb
WHERE id = 'fefef9a4-09fd-4c70-96c9-e41082563770';

UPDATE semanas SET videos = '[{"titulo":"🔴 Comprensión de lectura en inglés para pruebas tipo ICFES | Nivel Pre-intermedio","titulo_en":"🔴 Comprensión de lectura en inglés para pruebas tipo ICFES | Nivel Pre-intermedio","url":"https://www.youtube.com/watch?v=oj487UxyIoM","url_en":"https://www.youtube.com/watch?v=oj487UxyIoM","duracion":"10 min"},{"titulo":"Aprueba CUALQUIER Examen de INGLÉS con este método (funciona)","titulo_en":"Aprueba CUALQUIER Examen de INGLÉS con este método (funciona)","url":"https://www.youtube.com/watch?v=FeU-beri7tM","url_en":"https://www.youtube.com/watch?v=FeU-beri7tM","duracion":"10 min"},{"titulo":"Como leer mejor en INGLÉS / READING","titulo_en":"Como leer mejor en INGLÉS / READING","url":"https://www.youtube.com/watch?v=CPdtUVhXtAo","url_en":"https://www.youtube.com/watch?v=CPdtUVhXtAo","duracion":"10 min"}]'::jsonb
WHERE id = '8db169fa-3762-41a2-adc8-e1b36e3e1300';

UPDATE semanas SET videos = '[{"titulo":"Inteligencia Artificial en la Educacion  - Explicado en 5 minutos - IA","titulo_en":"Inteligencia Artificial en la Educacion  - Explicado en 5 minutos - IA","url":"https://www.youtube.com/watch?v=YZzB1Uca7n0","url_en":"https://www.youtube.com/watch?v=YZzB1Uca7n0","duracion":"10 min"},{"titulo":"¿Cómo desarrollar el pensamiento crítico?","titulo_en":"¿Cómo desarrollar el pensamiento crítico?","url":"https://www.youtube.com/watch?v=i-htv81L04g","url_en":"https://www.youtube.com/watch?v=i-htv81L04g","duracion":"10 min"},{"titulo":"¿Qué es y qué estudia la Psicología Cognitiva?","titulo_en":"¿Qué es y qué estudia la Psicología Cognitiva?","url":"https://www.youtube.com/watch?v=uvYep7c0Wa8","url_en":"https://www.youtube.com/watch?v=uvYep7c0Wa8","duracion":"10 min"}]'::jsonb
WHERE id = 'a237ae56-efc7-4a17-9d28-947660374c7c';

UPDATE semanas SET videos = '[{"titulo":"🔴 ACTIVIDADES ECONÓMICAS 🤓 | Primarias 🐔 Secundarias 🏭 Terciarias 🚛","titulo_en":"🔴 ACTIVIDADES ECONÓMICAS 🤓 | Primarias 🐔 Secundarias 🏭 Terciarias 🚛","url":"https://www.youtube.com/watch?v=l_Mv06EwzNM","url_en":"https://www.youtube.com/watch?v=l_Mv06EwzNM","duracion":"10 min"}]'::jsonb
WHERE id = '56c4de7f-ef9b-4bcc-befa-640facd8e2e9';

UPDATE semanas SET videos = '[{"titulo":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","titulo_en":"HÁBITOS SALUDABLES para adolescentes y niños 🏃🏻‍♂️🍏 Aprende a cuidarte ❤️","url":"https://www.youtube.com/watch?v=YWGOThGG8-Y","url_en":"https://www.youtube.com/watch?v=YWGOThGG8-Y","duracion":"10 min"},{"titulo":"IV Estudio Nacional: Prevención y Consumo de Drogas en Estudiantes de Secundaria del Perú.","titulo_en":"IV Estudio Nacional: Prevención y Consumo de Drogas en Estudiantes de Secundaria del Perú.","url":"https://www.youtube.com/watch?v=tkJPrH5SXR4","url_en":"https://www.youtube.com/watch?v=tkJPrH5SXR4","duracion":"10 min"},{"titulo":"Cómo hacer una Monografía desde 0","titulo_en":"Cómo hacer una Monografía desde 0","url":"https://www.youtube.com/watch?v=ckket3N9Uog","url_en":"https://www.youtube.com/watch?v=ckket3N9Uog","duracion":"10 min"}]'::jsonb
WHERE id = '59283110-6982-43bc-8cb0-cc71c852a27d';

UPDATE semanas SET videos = '[{"titulo":"PERÍMETRO Y ÁREA CON EXPRESIONES ALGEBRAICAS Super facil - Para principiantes","titulo_en":"PERÍMETRO Y ÁREA CON EXPRESIONES ALGEBRAICAS Super facil - Para principiantes","url":"https://www.youtube.com/watch?v=7iC-GAsvzcM","url_en":"https://www.youtube.com/watch?v=7iC-GAsvzcM","duracion":"10 min"},{"titulo":"PLANTEAR PERIMETRO ALGEBRAICO Super fácil - Para principiantes","titulo_en":"PLANTEAR PERIMETRO ALGEBRAICO Super fácil - Para principiantes","url":"https://www.youtube.com/watch?v=x0_cpbySMpc","url_en":"https://www.youtube.com/watch?v=x0_cpbySMpc","duracion":"10 min"},{"titulo":"PERÍMETRO, ÁREA Y VOLUMEN Super Fácil - Para principiantes","titulo_en":"PERÍMETRO, ÁREA Y VOLUMEN Super Fácil - Para principiantes","url":"https://www.youtube.com/watch?v=yY5beo7bXao","url_en":"https://www.youtube.com/watch?v=yY5beo7bXao","duracion":"10 min"}]'::jsonb
WHERE id = '15b75f4c-aad4-4f2f-8f8e-adeb5221121e';

UPDATE semanas SET videos = '[{"titulo":"Uso responsable de la tecnología para niños - Primer móvil - Ciberbullying - Fake news - Privacidad","titulo_en":"Uso responsable de la tecnología para niños - Primer móvil - Ciberbullying - Fake news - Privacidad","url":"https://www.youtube.com/watch?v=tBObvkx_nOg","url_en":"https://www.youtube.com/watch?v=tBObvkx_nOg","duracion":"10 min"},{"titulo":"Qué es la Ciberseguridad y Cómo Funciona","titulo_en":"Qué es la Ciberseguridad y Cómo Funciona","url":"https://www.youtube.com/watch?v=3G8yJaudGC0","url_en":"https://www.youtube.com/watch?v=3G8yJaudGC0","duracion":"10 min"},{"titulo":"¿Qué son las TIC y para qué sirven? Tipos y ejemplos (Tecnologías de la Información y Comunicación)","titulo_en":"¿Qué son las TIC y para qué sirven? Tipos y ejemplos (Tecnologías de la Información y Comunicación)","url":"https://www.youtube.com/watch?v=q8MeNBwRtPU","url_en":"https://www.youtube.com/watch?v=q8MeNBwRtPU","duracion":"10 min"}]'::jsonb
WHERE id = 'fb05e6ac-a745-4a12-9854-b340f6d007cf';

UPDATE semanas SET videos = '[{"titulo":"INGLES PARA NEGOCIOS | VOCABULARIO BASICO | Aumenta tu vocabulario para cerrar tratos!","titulo_en":"INGLES PARA NEGOCIOS | VOCABULARIO BASICO | Aumenta tu vocabulario para cerrar tratos!","url":"https://www.youtube.com/watch?v=6pPI2rZW2uU","url_en":"https://www.youtube.com/watch?v=6pPI2rZW2uU","duracion":"10 min"},{"titulo":"👩‍🏫 Profesiones en Inglés para Niños: Aprende Fácil y Divertido 👨‍🔧✨","titulo_en":"👩‍🏫 Profesiones en Inglés para Niños: Aprende Fácil y Divertido 👨‍🔧✨","url":"https://www.youtube.com/watch?v=7sg7BFCx2J0","url_en":"https://www.youtube.com/watch?v=7sg7BFCx2J0","duracion":"10 min"},{"titulo":"Test de 100 VERBOS BÁSICOS en INGLÉS 🏃‍♂️📚🤔 | Quiz de Inglés ✅ - 100 Verbos Más Comunes","titulo_en":"Test de 100 VERBOS BÁSICOS en INGLÉS 🏃‍♂️📚🤔 | Quiz de Inglés ✅ - 100 Verbos Más Comunes","url":"https://www.youtube.com/watch?v=rvnDKdhrtzI","url_en":"https://www.youtube.com/watch?v=rvnDKdhrtzI","duracion":"10 min"}]'::jsonb
WHERE id = '23a2f674-a669-4c3c-adda-5927bb032ad0';

UPDATE semanas SET videos = '[{"titulo":"📚 COMPRENSIÓN de un TEXTO","titulo_en":"📚 COMPRENSIÓN de un TEXTO","url":"https://www.youtube.com/watch?v=J7jpXHjmUns","url_en":"https://www.youtube.com/watch?v=J7jpXHjmUns","duracion":"10 min"},{"titulo":"8 estrategias para MEJORAR tu COMPRENSIÓN LECTORA","titulo_en":"8 estrategias para MEJORAR tu COMPRENSIÓN LECTORA","url":"https://www.youtube.com/watch?v=rkWb3uAGSSw","url_en":"https://www.youtube.com/watch?v=rkWb3uAGSSw","duracion":"10 min"},{"titulo":"IDENTIFICA el TEMA y SUBTEMAS de un texto con un EJEMPLO DE LECTURA 100% práctico","titulo_en":"IDENTIFICA el TEMA y SUBTEMAS de un texto con un EJEMPLO DE LECTURA 100% práctico","url":"https://www.youtube.com/watch?v=q9bokwchhs4","url_en":"https://www.youtube.com/watch?v=q9bokwchhs4","duracion":"10 min"}]'::jsonb
WHERE id = '9a7c6693-d8b0-4356-bd65-7a8f40dcd542';

UPDATE semanas SET videos = '[{"titulo":"¿Ves lo que yo? (Cortometraje sobre violencia de género)","titulo_en":"¿Ves lo que yo? (Cortometraje sobre violencia de género)","url":"https://www.youtube.com/watch?v=Id0KeN49jHY","url_en":"https://www.youtube.com/watch?v=Id0KeN49jHY","duracion":"10 min"},{"titulo":"Video informativo sobre orientación sexual, identidad de genero, rol de genero 💫✨","titulo_en":"Video informativo sobre orientación sexual, identidad de genero, rol de genero 💫✨","url":"https://www.youtube.com/watch?v=tnpAQ4PqXi8","url_en":"https://www.youtube.com/watch?v=tnpAQ4PqXi8","duracion":"10 min"},{"titulo":"Discriminación de  género","titulo_en":"Discriminación de  género","url":"https://www.youtube.com/watch?v=i57aPy5Jl3w","url_en":"https://www.youtube.com/watch?v=i57aPy5Jl3w","duracion":"10 min"}]'::jsonb
WHERE id = 'b3f2e5db-a01d-41d4-9425-95cd8cf0d590';

UPDATE semanas SET videos = '[{"titulo":"Distancia entre dos puntos | Ejemplo 1","titulo_en":"Distancia entre dos puntos | Ejemplo 1","url":"https://www.youtube.com/watch?v=HPS7B57keEE","url_en":"https://www.youtube.com/watch?v=HPS7B57keEE","duracion":"10 min"},{"titulo":"#matemáticas  III. Conceptos básicos de #geometria  analítica, plano cartesiano, punto. Bachillerato","titulo_en":"#matemáticas  III. Conceptos básicos de #geometria  analítica, plano cartesiano, punto. Bachillerato","url":"https://www.youtube.com/watch?v=yv3e7JRbLS0","url_en":"https://www.youtube.com/watch?v=yv3e7JRbLS0","duracion":"10 min"},{"titulo":"Distancia entre dos puntos | Introducción","titulo_en":"Distancia entre dos puntos | Introducción","url":"https://www.youtube.com/watch?v=dRv6f7Y2l6U","url_en":"https://www.youtube.com/watch?v=dRv6f7Y2l6U","duracion":"10 min"}]'::jsonb
WHERE id = '675bce7e-46b6-4317-9199-da4d076c637a';

UPDATE semanas SET videos = '[{"titulo":"5 claves para redactar mejor tus textos","titulo_en":"5 claves para redactar mejor tus textos","url":"https://www.youtube.com/watch?v=pJPm2CGTPgc","url_en":"https://www.youtube.com/watch?v=pJPm2CGTPgc","duracion":"10 min"},{"titulo":"6 pasos para realizar una redacción eficaz ✍️","titulo_en":"6 pasos para realizar una redacción eficaz ✍️","url":"https://www.youtube.com/watch?v=P0ehQ1DULEY","url_en":"https://www.youtube.com/watch?v=P0ehQ1DULEY","duracion":"10 min"},{"titulo":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","titulo_en":"TIPOS DE TEXTOS | Narrativo, descriptivo, expositivo, argumentativo e instructivo","url":"https://www.youtube.com/watch?v=tMP1lds7pLM","url_en":"https://www.youtube.com/watch?v=tMP1lds7pLM","duracion":"10 min"}]'::jsonb
WHERE id = 'fc0bd98c-9d00-48eb-8f2d-2edcba27e544';

UPDATE semanas SET videos = '[{"titulo":"👉​👉 ¿Cuánto sabes de lenguaje y comunicación? 20 preguntas de conocimiento general. 🤯🧠​​🎓","titulo_en":"👉​👉 ¿Cuánto sabes de lenguaje y comunicación? 20 preguntas de conocimiento general. 🤯🧠​​🎓","url":"https://www.youtube.com/watch?v=vFtCipDU5RI","url_en":"https://www.youtube.com/watch?v=vFtCipDU5RI","duracion":"10 min"},{"titulo":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","titulo_en":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","url":"https://www.youtube.com/watch?v=-8YazHRMcXk","url_en":"https://www.youtube.com/watch?v=-8YazHRMcXk","duracion":"10 min"},{"titulo":"Cómo Estudiar Rápido y Bien para Un Examen | Saca la Mejor Nota para Aprobar Fácil Exámenes Test Día","titulo_en":"Cómo Estudiar Rápido y Bien para Un Examen | Saca la Mejor Nota para Aprobar Fácil Exámenes Test Día","url":"https://www.youtube.com/watch?v=KocAhjNyD_Y","url_en":"https://www.youtube.com/watch?v=KocAhjNyD_Y","duracion":"10 min"}]'::jsonb
WHERE id = '2ba2eed4-3f40-4495-865e-f548bc24ab33';

UPDATE semanas SET videos = '[{"titulo":"📚 COMPRENSIÓN de un TEXTO","titulo_en":"📚 COMPRENSIÓN de un TEXTO","url":"https://www.youtube.com/watch?v=J7jpXHjmUns","url_en":"https://www.youtube.com/watch?v=J7jpXHjmUns","duracion":"10 min"},{"titulo":"COMPRENSIÓN DE LECTURA: EL TEMA","titulo_en":"COMPRENSIÓN DE LECTURA: EL TEMA","url":"https://www.youtube.com/watch?v=JUcl3Wah9Jo","url_en":"https://www.youtube.com/watch?v=JUcl3Wah9Jo","duracion":"10 min"},{"titulo":"🔴 Comprensión de lectura en inglés para pruebas tipo ICFES | Nivel Pre-intermedio","titulo_en":"🔴 Comprensión de lectura en inglés para pruebas tipo ICFES | Nivel Pre-intermedio","url":"https://www.youtube.com/watch?v=oj487UxyIoM","url_en":"https://www.youtube.com/watch?v=oj487UxyIoM","duracion":"10 min"}]'::jsonb
WHERE id = 'b7f769c0-3e39-4cf0-9a9f-199fb7850077';

UPDATE semanas SET videos = '[{"titulo":"APRENDE las bases del inglés en 10 minutos 🔴 FastBrain TV","titulo_en":"APRENDE las bases del inglés en 10 minutos 🔴 FastBrain TV","url":"https://www.youtube.com/watch?v=AkF3ZNcZUHc","url_en":"https://www.youtube.com/watch?v=AkF3ZNcZUHc","duracion":"10 min"},{"titulo":"⌛APRENDE la GRAMÁTICA INGLESA en 15 minutos 😲 (Cambia tu Inglés para SIEMPRE!!!)","titulo_en":"⌛APRENDE la GRAMÁTICA INGLESA en 15 minutos 😲 (Cambia tu Inglés para SIEMPRE!!!)","url":"https://www.youtube.com/watch?v=SQOEqIuh4gg","url_en":"https://www.youtube.com/watch?v=SQOEqIuh4gg","duracion":"10 min"},{"titulo":"Aprueba CUALQUIER Examen de INGLÉS con este método (funciona)","titulo_en":"Aprueba CUALQUIER Examen de INGLÉS con este método (funciona)","url":"https://www.youtube.com/watch?v=FeU-beri7tM","url_en":"https://www.youtube.com/watch?v=FeU-beri7tM","duracion":"10 min"}]'::jsonb
WHERE id = '489f7cab-98cf-4298-b6ef-7586c93ab94a';

UPDATE semanas SET videos = '[{"titulo":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","titulo_en":"¡Aprende los conceptos básicos de redes en menos de 15 minutos!","url":"https://www.youtube.com/watch?v=_JNPvSxG6oM","url_en":"https://www.youtube.com/watch?v=_JNPvSxG6oM","duracion":"10 min"},{"titulo":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","titulo_en":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","url":"https://www.youtube.com/watch?v=-8YazHRMcXk","url_en":"https://www.youtube.com/watch?v=-8YazHRMcXk","duracion":"10 min"},{"titulo":"1. Metodología de Investigación: Conceptos Generales","titulo_en":"1. Metodología de Investigación: Conceptos Generales","url":"https://www.youtube.com/watch?v=q1UXTIJwJyg","url_en":"https://www.youtube.com/watch?v=q1UXTIJwJyg","duracion":"10 min"}]'::jsonb
WHERE id = 'cd586867-1246-4582-ba92-b6d53b0ed6f1';

UPDATE semanas SET videos = '[{"titulo":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","titulo_en":"Lógica de Programación 👩‍💻 Aprende a programar en 10 minutos","url":"https://www.youtube.com/watch?v=as1opL254NA","url_en":"https://www.youtube.com/watch?v=as1opL254NA","duracion":"10 min"},{"titulo":"ANTES de ESTUDIAR INGENIERÍA de SISTEMAS MIRA ESTO | ¿Qué debo saber para estudiar ing. de sistemas?","titulo_en":"ANTES de ESTUDIAR INGENIERÍA de SISTEMAS MIRA ESTO | ¿Qué debo saber para estudiar ing. de sistemas?","url":"https://www.youtube.com/watch?v=y8GESWoleoQ","url_en":"https://www.youtube.com/watch?v=y8GESWoleoQ","duracion":"10 min"},{"titulo":"Redacta un Ensayo en 3 sencillos pasos","titulo_en":"Redacta un Ensayo en 3 sencillos pasos","url":"https://www.youtube.com/watch?v=FwgeiavmoiI","url_en":"https://www.youtube.com/watch?v=FwgeiavmoiI","duracion":"10 min"}]'::jsonb
WHERE id = '5252f2e9-555b-4620-909b-49f9dcf254f0';

UPDATE semanas SET videos = '[{"titulo":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","titulo_en":"Historia de la EDUCACIÓN - Resumen | Desde sus orígenes hasta nuestros días.","url":"https://www.youtube.com/watch?v=TYo3h6mPBvc","url_en":"https://www.youtube.com/watch?v=TYo3h6mPBvc","duracion":"10 min"},{"titulo":"Historia de la psicología (Resumido)","titulo_en":"Historia de la psicología (Resumido)","url":"https://www.youtube.com/watch?v=CbSoaURC7gM","url_en":"https://www.youtube.com/watch?v=CbSoaURC7gM","duracion":"10 min"},{"titulo":"Qué es la Literatura: Definición, Características &amp; Más | Descubre el Mundo de la Literatura","titulo_en":"Qué es la Literatura: Definición, Características &amp; Más | Descubre el Mundo de la Literatura","url":"https://www.youtube.com/watch?v=4KoU144az18","url_en":"https://www.youtube.com/watch?v=4KoU144az18","duracion":"10 min"}]'::jsonb
WHERE id = '07ee6729-7efc-4bec-b611-ca730db15a6e';

UPDATE semanas SET videos = '[{"titulo":"Aprueba CUALQUIER Examen de INGLÉS con este método (funciona)","titulo_en":"Aprueba CUALQUIER Examen de INGLÉS con este método (funciona)","url":"https://www.youtube.com/watch?v=FeU-beri7tM","url_en":"https://www.youtube.com/watch?v=FeU-beri7tM","duracion":"10 min"},{"titulo":"Repaso Gramática B2 inglés - explicación y ejemplos 2021","titulo_en":"Repaso Gramática B2 inglés - explicación y ejemplos 2021","url":"https://www.youtube.com/watch?v=PHPTlFi7-_0","url_en":"https://www.youtube.com/watch?v=PHPTlFi7-_0","duracion":"10 min"},{"titulo":"⌛APRENDE la GRAMÁTICA INGLESA en 15 minutos 😲 (Cambia tu Inglés para SIEMPRE!!!)","titulo_en":"⌛APRENDE la GRAMÁTICA INGLESA en 15 minutos 😲 (Cambia tu Inglés para SIEMPRE!!!)","url":"https://www.youtube.com/watch?v=SQOEqIuh4gg","url_en":"https://www.youtube.com/watch?v=SQOEqIuh4gg","duracion":"10 min"}]'::jsonb
WHERE id = '7c74fb2b-af23-438e-b972-a9c364873d05';

UPDATE semanas SET videos = '[{"titulo":"TODO LO QUE DEBES SABER: ACREDITA BACH","titulo_en":"TODO LO QUE DEBES SABER: ACREDITA BACH","url":"https://www.youtube.com/watch?v=p-fzfzn6CEU","url_en":"https://www.youtube.com/watch?v=p-fzfzn6CEU","duracion":"10 min"},{"titulo":"1. ESTO ES LO QUE DEBES SABER DE MATEMÁTICAS ANTES DE ENTRAR A LA UNIVERSIDAD. Parte 1","titulo_en":"1. ESTO ES LO QUE DEBES SABER DE MATEMÁTICAS ANTES DE ENTRAR A LA UNIVERSIDAD. Parte 1","url":"https://www.youtube.com/watch?v=0d5VWxcSUIk","url_en":"https://www.youtube.com/watch?v=0d5VWxcSUIk","duracion":"10 min"},{"titulo":"Cómo APRENDER Matemáticas desde CERO | El MEJOR Método","titulo_en":"Cómo APRENDER Matemáticas desde CERO | El MEJOR Método","url":"https://www.youtube.com/watch?v=q-l22RzY5EI","url_en":"https://www.youtube.com/watch?v=q-l22RzY5EI","duracion":"10 min"}]'::jsonb
WHERE id = '736eda0f-b8af-4576-84b6-a306b0e8047f';

UPDATE semanas SET videos = '[{"titulo":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","titulo_en":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","url":"https://www.youtube.com/watch?v=-8YazHRMcXk","url_en":"https://www.youtube.com/watch?v=-8YazHRMcXk","duracion":"10 min"},{"titulo":"TODO LO QUE DEBES SABER: ACREDITA BACH","titulo_en":"TODO LO QUE DEBES SABER: ACREDITA BACH","url":"https://www.youtube.com/watch?v=p-fzfzn6CEU","url_en":"https://www.youtube.com/watch?v=p-fzfzn6CEU","duracion":"10 min"},{"titulo":"Cómo APRENDER Matemáticas desde CERO | El MEJOR Método","titulo_en":"Cómo APRENDER Matemáticas desde CERO | El MEJOR Método","url":"https://www.youtube.com/watch?v=q-l22RzY5EI","url_en":"https://www.youtube.com/watch?v=q-l22RzY5EI","duracion":"10 min"}]'::jsonb
WHERE id = 'ddeaaaf2-3fd1-4a28-984d-debf61490a39';

UPDATE semanas SET videos = '[{"titulo":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","titulo_en":"CONCEPTOS BÁSICOS DE NUTRICIÓN Y ALIMENTACIÓN | GuiaMed","url":"https://www.youtube.com/watch?v=qHimbDfTXYg","url_en":"https://www.youtube.com/watch?v=qHimbDfTXYg","duracion":"10 min"},{"titulo":"¿Cómo MEJORAR tu manera de Estudiar? | Drpologuerrero","titulo_en":"¿Cómo MEJORAR tu manera de Estudiar? | Drpologuerrero","url":"https://www.youtube.com/watch?v=MAjm9Sfc9Mg","url_en":"https://www.youtube.com/watch?v=MAjm9Sfc9Mg","duracion":"10 min"},{"titulo":"Redacta un Ensayo en 3 sencillos pasos","titulo_en":"Redacta un Ensayo en 3 sencillos pasos","url":"https://www.youtube.com/watch?v=FwgeiavmoiI","url_en":"https://www.youtube.com/watch?v=FwgeiavmoiI","duracion":"10 min"}]'::jsonb
WHERE id = '1073ea0b-efd5-4054-8fd4-0523602facd3';

UPDATE semanas SET videos = '[{"titulo":"Cómo APRENDER Matemáticas desde CERO | El MEJOR Método","titulo_en":"Cómo APRENDER Matemáticas desde CERO | El MEJOR Método","url":"https://www.youtube.com/watch?v=q-l22RzY5EI","url_en":"https://www.youtube.com/watch?v=q-l22RzY5EI","duracion":"10 min"},{"titulo":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","titulo_en":"Cómo Estudiar de MANERA EFECTIVA (menos de 2 horas)","url":"https://www.youtube.com/watch?v=-8YazHRMcXk","url_en":"https://www.youtube.com/watch?v=-8YazHRMcXk","duracion":"10 min"},{"titulo":"1. ESTO ES LO QUE DEBES SABER DE MATEMÁTICAS ANTES DE ENTRAR A LA UNIVERSIDAD. Parte 1","titulo_en":"1. ESTO ES LO QUE DEBES SABER DE MATEMÁTICAS ANTES DE ENTRAR A LA UNIVERSIDAD. Parte 1","url":"https://www.youtube.com/watch?v=0d5VWxcSUIk","url_en":"https://www.youtube.com/watch?v=0d5VWxcSUIk","duracion":"10 min"}]'::jsonb
WHERE id = 'e1dcb0a6-efc8-4120-b81e-c7957073e819';

UPDATE semanas SET videos = '[{"titulo":"✨🧬 Así es el proceso de FECUNDACIÓN - Fertilización Paso a paso","titulo_en":"✨🧬 Así es el proceso de FECUNDACIÓN - Fertilización Paso a paso","url":"https://www.youtube.com/watch?v=t2kO6PkzFoc","url_en":"https://www.youtube.com/watch?v=t2kO6PkzFoc","duracion":"10 min"},{"titulo":"La Teoría del Desarrollo Cognitivo de Piaget","titulo_en":"La Teoría del Desarrollo Cognitivo de Piaget","url":"https://www.youtube.com/watch?v=yYFhPO5pArc","url_en":"https://www.youtube.com/watch?v=yYFhPO5pArc","duracion":"10 min"},{"titulo":"¿Qué es el Método DEDUCTIVO e INDUCTIVO? ¿Qué DIFERENCIAS existen entre ambos? | Curso Economía","titulo_en":"¿Qué es el Método DEDUCTIVO e INDUCTIVO? ¿Qué DIFERENCIAS existen entre ambos? | Curso Economía","url":"https://www.youtube.com/watch?v=yKCmn7utNRc","url_en":"https://www.youtube.com/watch?v=yKCmn7utNRc","duracion":"10 min"}]'::jsonb
WHERE id = 'fd818ce0-acbe-4be9-8dab-e6965e6c7c51';
